Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-06, with the labels that each got.

#258 ✨ Add general svg icon rendering component
  __mocks__/fileMock.js
  __setups__/icons.js
  babel.config.js
  jest.config.js
  src/assets/icons/box.js
  src/assets/icons/checkmark.js
  src/assets/icons/clinical.js
  src/assets/icons/edit.js
  src/assets/icons/icon-box.svg
  src/assets/icons/icon-checkmark.svg
  src/assets/icons/icon-clinical.svg
  src/assets/icons/icon-edit.svg
  src/assets/icons/icon-error.svg
  src/assets/icons/icon-misc.svg
  src/assets/icons/icon-notification.svg
  src/assets/icons/icon-sequencing.svg
  src/assets/icons/icon-upload.svg
  src/assets/icons/index.js
  src/assets/icons/misc.js
  src/assets/icons/notification.js
  src/assets/icons/sequencing.js
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/FileAnnotation/SelectElement.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/NotificationBar.js
  src/components/FileDetail/VersionItem.js
  src/components/FileDetail/VersionList.js
  src/components/FileDetail/__tests__/VersionItem.test.js
  src/components/FileDetail/__tests__/VersionList.test.js
  src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileDetail/__tests__/fileByKfId.json
  src/components/FileDetail/file-detail.css
  src/components/Icon/Icon.js
  src/views/__tests__/FileUpload.test.js
Labels: refactor

#260 ♻️ Refactor editor and upload container
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  __mocks__/kf-api-study-creator/responses/updateFile.json
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/FileEditor.test.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/containers/FileEditorContainer.js
  src/containers/UploadContainer.js
  src/state/queries.js
  src/views/AnnotationView.js
  src/views/StudyFilesListView.js
Labels: refactor

#237 ✨ Add modal view for version upload and annotation
  src/components/FileAnnotation/FileEditor.js
  src/components/FileDetail/AnnotateVersionModalContainer.js
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/FileDetailModal.js
  src/components/FileDetail/UploadVersionModalContainer.js
  src/components/FileDetail/VersionList.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileDetail/file-detail.css
Labels: component, design, feature

#231 ✨ Add pagination on file list
  package.json
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/__tests__/studyByKfId.json
  src/components/FileList/filelist.css
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  yarn.lock
Labels: feature

#222 ♻️ Refactor study header
  src/components/StudyHeader/StudyHeader.css
  src/components/StudyHeader/StudyHeader.jsx
  src/views/NavBarView.js
Labels: design, refactor

#262 ✨ Add logout button
  src/Routes/index.js
Labels: feature

#265 🚚 Rename .jsx files to .js
  src/components/FileActionButtons/FileActionButtons.js
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/ToggleButtons/ToggleButtons.js
  src/containers/FileActionsContainer.js
Labels: refactor

#273 ✨ Add new version flow
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/FileDetailModal.js
  src/modals/NewVersionModal.js
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/modals/NewVersionModal/UploadStep.js
  src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
  src/modals/index.js
  src/state/mutations.js
Labels: feature, refactor

#279 ♻️ Refactor badge component taking version state data
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  src/common/fileUtils.js
  src/components/Badge/Badge.js
  src/components/Badge/__tests__/Badge.test.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/Badge/badge.css
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/state/queries.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: refactor

#280 ♻️ Refactor avatar component taking creator data
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/VersionItem.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileList/__tests__/studyByKfId.json
  src/state/queries.js
Labels: refactor

#274 ✨ Add user profile page
  src/App.css
  src/Routes/index.js
  src/forms/UpdateProfileForm.js
  src/state/mutations.js
  src/state/queries.js
  src/views/ProfileView.js
  src/views/index.js
Labels: feature

#281 ♻️ Refactor version list component
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/VersionItem.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileDetail/file-detail.css
  src/components/VersionList/VersionItem.js
  src/components/VersionList/VersionList.js
  src/components/VersionList/_tests_/VersionItem.test.js
  src/components/VersionList/_tests_/VersionList.test.js
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/components/VersionList/version-list.css
  src/state/queries.js
Labels: design, refactor

#282 ♻️ Refactor version upload and annotation modal style
  src/App.css
  src/components/FileDetail/FileDetailModal.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileDetail/file-detail.css
  src/components/Modal/Modal.js
  src/forms/NewDocumentForm.js
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
Labels: refactor

#283 ✨ Study subscriptions manager
  src/components/StudyList/StudyTable.js
  src/containers/StudySubscriptionContainer.js
  src/state/mutations.js
  src/state/queries.js
  src/views/ProfileView.js
Labels: feature

#284 ✨ Add version detail modal
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/FileDetailModal.js
  src/components/Modal/Modal.js
  src/components/Modal/ModalFooter.js
  src/components/Modal/modal.css
  src/components/VersionList/VersionItem.js
  src/components/VersionList/VersionList.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/modals/VersionInfoModal/VersionInfoModal.js
  src/modals/index.js
Labels: design, feature

#285 ♻️ Refactor document edit modal
  src/App.css
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/FileEditor.test.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileAnnotation/fileannotation.css
  src/components/FileDetail/AnnotateVersionModalContainer.js
  src/components/FileDetail/FileDetailModal.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/containers/FileEditorContainer.js
  src/forms/EditDocumentForm.js
  src/forms/NewDocumentForm.js
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
  src/forms/index.js
  src/modals/EditDocumentModal.js
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/VersionInfoModal.js
  src/modals/index.js
Labels: design, feature, refactor

#292 ✨ Conditional rendering notification bar on top of file list
  src/components/FileDetail/file-detail.css
  src/components/FileList/FileList.js
  src/components/NotificationBar/NotificationBar.js
  src/components/NotificationBar/notification-bar.css
Labels: component, design

#288 ✨ Add approval status dropdown to file annotation modal
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/updateVersion.json
  src/common/fileUtils.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/forms/EditDocumentForm.js
  src/modals/EditDocumentModal.js
  src/state/mutations.js
Labels: design, feature

#294 ✨ Add profile dropdown to header
  src/Routes/index.js
  src/components/HeaderButton/HeaderButton.js
Labels: component, design

#296 ✨ Add "uploading" stage to submit button when uploading new file or new version
  src/forms/NewDocumentForm.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/views/NewDocumentView.js
Labels: feature

#289 ♻️ Refactor upload verbiage
  src/Routes/index.js
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/containers/StudySubscriptionContainer.js
  src/containers/UploadContainer.js
  src/modals/NewVersionModal/UploadStep.js
  src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
  src/views/NewDocumentView.js
  src/views/StudyFilesListView.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design

#297 💄 Refactor pagination styling
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/filelist.css
  src/components/Pagination/Pagination.js
  src/components/Pagination/pagination.css
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design

#298 ✨ Redirect user back to the original requested page after login
  src/Routes/PrivateRoute.js
  src/components/Login/Login.js
  src/state/auth.js
  src/views/LoginView.js
Labels: feature

#326 🐛 Fix file type icon mismatch
  src/common/fileUtils.js
Labels: bug

#328 🐛 Fix minor typo and style issue on file type and file description
  src/common/fileUtils.js
  src/components/FileDetail/file-detail.css
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
Labels: bug

#299 💄 refactor modal positioning
  src/components/FileDetail/file-detail.css
  src/components/FileList/__tests__/FileList.test.js
  src/components/Modal/modal.css
  src/modals/NewVersionModal/NewVersionFlow.js
  src/modals/NewVersionModal/UploadStep.js
  src/modals/VersionInfoModal.js
Labels: design, refactor

#327 💄 Profile view bug fix and style updates
  src/App.css
  src/components/StudyList/StudyTable.js
  src/forms/UpdateProfileForm.js
  src/views/ProfileView.js
Labels: bug, refactor

#308 💄 Use Semantic for Login View
  src/components/Login/index.js
  src/components/LoginCard/LoginCard.js
  src/components/LoginCard/LoginCard.test.js
  src/components/LoginCard/__snapshots__/LoginCard.test.js.snap
  src/components/LoginCard/index.js
  src/views/LoginView.js
Labels: design, refactor

#309 💄 Use Semantic for Token View
  src/components/TokenList/TokenList.js
  src/components/TokenList/TokenList.test.js
  src/components/TokenList/__snapshots__/TokenList.test.js.snap
  src/components/TokenList/index.js
  src/components/Tokens/NewTokenForm.js
  src/components/Tokens/TokenList.js
  src/containers/NewTokenFormContainer.js
  src/forms/NewTokenForm.js
  src/state/queries.js
  src/views/TokensListView.js
Labels: design, refactor

#323 💄 Semantic header
  src/Routes/index.js
  src/assets/logo.svg
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/Header.js
  src/components/LoginCard/LoginCard.js
  src/components/LoginCard/__snapshots__/LoginCard.test.js.snap
  src/views/CallbackView.js
  src/views/LoginView.js
  src/views/TokensListView.js
Labels: design, refactor

#337 💄 Use semantic for badges
  src/common/fileUtils.js
  src/components/Badge/Badge.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design, refactor
