Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-10, with the labels that each got.

#467 ✨ Add alert for study data completeness, files, and projects to study list
  __mocks__/kf-api-study-creator/responses/allStudies.json
  src/App.css
  src/Routes/index.js
  src/common/enums.js
  src/common/fileUtils.js
  src/common/notificationUtils.js
  src/components/Badge/Badge.js
  src/components/Badge/__tests__/Badge.test.js
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/SelectElement.js
  src/components/FileList/FileElement.js
  src/components/ListFilterBar/ListFilterBar.js
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/FileSimpleList.js
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/StudyList/__tests__/allStudies.json
  src/components/VersionList/VersionItem.js
  src/forms/EditDocument/EditDocumentForm.js
  src/modals/LinkProjectModal.js
  src/modals/NewProjectModal.js
  src/modals/VersionInfoModal.js
  src/state/fragments.js
  src/state/queries.js
  src/views/CavaticaBixView.js
  src/views/StudyListView.js
Labels: feature

#495 ✨ Add alert for study data completeness to study info page
  src/App.css
  src/common/notificationUtils.js
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyInfo/ProgressBar.js
  src/forms/FormField.js
  src/forms/StudyFormSteps.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/ExternalStep.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/forms/StudyInfoForm/Steps/LogisticsStep.js
  src/forms/StudyInfoForm/Steps/index.js
  src/forms/StudyInfoForm/index.js
  src/views/CavaticaBixView.js
  src/views/NewStudyView.js
  src/views/StudyInfoView.js
Labels: feature

#496 🐛 Add query name to solve Error writing result to store for query
  src/state/mutations.js
  src/state/queries.js
Labels: bug

#484 ✨FileElement copy download link action button
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/FileActionButtons/FileActionButtons.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
  src/state/queries.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: feature, usability improvement

#499 📷 Improve Snapshot Coverage 1/3
  src/components/AvatarTimeAgo/__tests__/AvatarTimeAgo.test.js
  src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
  src/components/Badge/__tests__/Badge.test.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectItem.test.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectItem.test.js.snap
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/CopyButton.test.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/CopyButton/__test__/CopyButton.test.js
  src/components/CopyButton/__test__/__snapshots__/CopyButton.test.js.snap
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/EventList.test.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
  src/components/FileActionButtons/FileActionButtons.js
  src/components/FileActionButtons/__tests__/FileActionButtons.test.js
  src/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap
  src/components/FileAnnotation/SelectElement.js
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/SelectElement.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: component, refactor

#500 📷 Improve Snapshot Coverage 2/3
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileUpload/FileUploadTarget.js
  src/components/FileUpload/__test__/FileUploadTarget.test.js
  src/components/FileUpload/__test__/__snapshots__/FileUploadTarget.test.js.snap
  src/components/Header/__tests__/Header.test.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/ListFilterBar/ListFilterBar.js
  src/components/ListFilterBar/__test__/ListFilterBar.test.js
  src/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyHeader/StudyHeader.test.js
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
  src/components/StudyHeader/__test__/StudyHeader.test.js
  src/components/StudyHeader/__test__/__snapshots__/StudyHeader.test.js.snap
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/FileSimpleList.js
  src/components/StudyInfo/__test__/CavaticaCounts.test.js
  src/components/StudyInfo/__test__/FileCounts.test.js
  src/components/StudyInfo/__test__/__snapshots__/CavaticaCounts.test.js.snap
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
  src/containers/UploadContainer.js
  src/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: component, refactor

#497 📷 Improve Snapshot Coverage 3/3
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyInfo/__test__/ProgressBar.test.js
  src/components/StudyInfo/__test__/__snapshots__/ProgressBar.test.js.snap
  src/components/StudyList/StudyCard.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/StudyNavBar.test.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/ToggleButtons.test.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/components/TokenList/TokenList.js
  src/components/TokenList/TokenList.test.js
  src/components/TokenList/__snapshots__/TokenList.test.js.snap
  src/components/TokenList/__test__/TokenList.test.js
  src/components/TokenList/__test__/__snapshots__/TokenList.test.js.snap
  src/components/VersionList/VersionItem.js
  src/components/VersionList/_tests_/VersionItem.test.js
  src/components/VersionList/_tests_/VersionList.test.js
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
Labels: component, refactor

#509 🐛 Fix download mutation by removing the id
  src/state/mutations.js
Labels: bug

#506 📝 Add pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#515 💄 Hide delete file button from non-admin users on file list and file detail page
  src/components/FileActionButtons/FileActionButtons.js
  src/components/FileDetail/FileDetail.js
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/containers/FileActionsContainer.js
  src/containers/FileDetailContainer.js
  src/views/FileDetailView.js
  src/views/StudyFilesListView.js
  src/views/__tests__/StudyFilesListView.test.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: feature, refactor

#511 💄 Refactor the style of study list in grid and table view with ADMIN alert
  src/App.css
  src/assets/CavaticaLogo.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/__test__/__snapshots__/CavaticaCounts.test.js.snap
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
Labels: component, design

#519 ✅ Add Codecov test as default pull request checking method
  .circleci/config.yml
  README.md
  jest.config.js
  package.json
  yarn.lock
Labels: devops

#507 💄 Remove Login with Ego button from login card
  .env.schema
  README.md
  netlify.toml
  package.json
  src/Routes/AdminRoute.js
  src/Routes/PrivateRoute.js
  src/Routes/index.js
  src/common/globals.js
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/LoginCard/LoginCard.js
  src/components/LoginCard/LoginCard.test.js
  src/components/LoginCard/__snapshots__/LoginCard.test.js.snap
  src/components/LoginCard/index.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/state/auth.js
  src/state/client.js
  src/views/LoginView.js
  src/views/LogoutView.js
  src/views/index.js
  yarn.lock
Labels: component, refactor

#516 💄 Default study info on editing for ADMIN and read-only for regular users
  src/App.css
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/ExternalStep.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/forms/StudyInfoForm/Steps/LogisticsStep.js
  src/views/StudyInfoView.js
Labels: design, feature, refactor

#527 ♻️ Move query logic for file detail to view
  src/documents/containers/FileDetailContainer.js
  src/documents/forms/EditDocumentForm.js
  src/documents/views/FileDetailView.js
Labels: refactor
