Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-12, with the labels that each got.

#555 💄 Add icon mappings for new event types
  src/common/enums.js
  src/views/__test__/__snapshots__/EventsView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
Labels: design

#548 ✨ Add study-creator-api version to footer
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/status.json
  src/components/Footer/Footer.js
  src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/state/queries.js
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__test__/__snapshots__/EventsView.test.js.snap
  src/views/__test__/__snapshots__/LoginView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
  src/views/__test__/__snapshots__/ProfileView.test.js.snap
  src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__test__/__snapshots__/TokenListView.test.js.snap
Labels: feature

#512 📈 Amplitude analytics base setup
  .env.schema
  jest.config.js
  package.json
  src/App.js
  src/Routes/AdminRoute.js
  src/Routes/PrivateRoute.js
  src/Routes/TrackedRoute.js
  src/Routes/index.js
  src/analyticsTracking/AmplitudeProxy.js
  src/analyticsTracking/AmplitudeUser.js
  src/analyticsTracking/AnalyticsProviderMock.js
  src/analyticsTracking/AnalyticsTrackingProvider.js
  src/analyticsTracking/__tests__/AmplitudeProxy.test.js
  src/analyticsTracking/__tests__/eventUtils.test.js
  src/analyticsTracking/__tests__/index.test.js
  src/analyticsTracking/eventConstants.js
  src/analyticsTracking/eventSchemaValidator.js
  src/analyticsTracking/eventUtils.js
  src/analyticsTracking/event_schemas/AUTH/AUTH__LOGIN.schema.json
  src/analyticsTracking/event_schemas/PAGE/PAGE__VIEW.schema.json
  src/analyticsTracking/event_schemas/common_defs.schema.json
  src/analyticsTracking/event_schemas/index.js
  src/analyticsTracking/event_schemas/saveSchema.js
  src/analyticsTracking/event_schemas/user/user.schema.json 
  src/analyticsTracking/index.js
  src/common/globals.js
  src/components/Header/Header.js
  src/documents/components/FileDetail/__tests__/EditExistingFile.test.js
  src/documents/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/documents/views/__tests__/StudyFilesListView.test.js
  src/state/auth.js
  src/views/LoginView.js
  src/views/__test__/NewStudyView.test.js
  src/views/__test__/StudyInfoView.test.js
  src/views/__test__/__snapshots__/LoginView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
  yarn.lock
Labels: documentation, feature

#557 📈Hotjar tracking script in head tag
  public/index.html
Labels: feature

#553 ✨ Add page titles to all views
  package.json
  src/Routes/index.js
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/StudyNavBar.test.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/views/StudyFilesListView.js
  src/views/CallbackView.js
  src/views/CavaticaBixView.js
  src/views/CavaticaProjectsView.js
  src/views/EventsView.js
  src/views/LoginView.js
  src/views/LogoutView.js
  src/views/LogsView.js
  src/views/NewStudyView.js
  src/views/ProfileView.js
  src/views/StudyInfoView.js
  src/views/StudyListView.js
  src/views/TokensListView.js
  src/views/__test__/TokenListView.test.js
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__test__/__snapshots__/LoginView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
  src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
  yarn.lock
Labels: feature

#560 🔥 Remove BETA user checking from study info page
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/StudyNavBar.test.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/views/StudyInfoView.js
  src/views/__test__/StudyInfoView.test.js
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
  src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
Labels: refactor

#561 🐛 Allow admin user to copy newly created token
  src/components/TokenList/TokenList.js
  src/components/TokenList/__test__/TokenList.test.js
  src/components/TokenList/__test__/__snapshots__/TokenList.test.js.snap
  src/forms/NewTokenForm.js
  src/views/TokensListView.js
  src/views/__test__/__snapshots__/TokenListView.test.js.snap
Labels: bug

#554 ✨ Add new study creation status view
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation.json
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_err.json
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_ing.json
  __mocks__/kf-api-study-creator/responses/studyByKfId_event_err.json
  src/App.css
  src/common/enums.js
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyHeader/__test__/StudyHeader.test.js
  src/components/StudyHeader/__test__/__snapshots__/StudyHeader.test.js.snap
  src/forms/StudyInfoForm/NewStudyForm.js
  src/modals/CreatingStudyModal.js
  src/modals/index.js
  src/views/NavBarView.js
  src/views/NewStudyView.js
  src/views/__test__/NavBarView.test.js
  src/views/__test__/NewStudyView.test.js
  src/views/__test__/__snapshots__/NavBarView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
Labels: feature
