Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-04, with the labels that each got.

#145 📄 Add LICENSE file
  LICENSE
Labels: documentation

#148 ♻️ Refactor token view adding copy button
  src/components/Tokens/TokenList.js
  src/views/TokensListView.js
Labels: refactor

#146 ♻️ Refactor loading state for study list and file list
  src/components/StudyList/StudyList.jsx
  src/views/StudyFilesListView.js
  src/views/StudyListView.js
Labels: refactor

#185 🔧 Ensure dependencies use babel 7
  .babelrc
  package.json
  yarn.lock
Labels: bug

#187 📦 Add react-testing-library for testing
  package.json
  yarn.lock
Labels: feature

#188 📷 Snapshot tests CopyButton component
  src/components/CopyButton/CopyButton.test.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
Labels: refactor

#192 📷 Add snapshot tests for FileAnnotation
  src/components/FileAnnotation/FileEditor.test.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
Labels: refactor

#201 ⬆️ Bump uikit version from 0.3.1 to 0.5.0 with related style adjustment
  package.json
  src/components/Badge/badge.css
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/SelectElement.js
  src/components/FileAnnotation/fileannotation.css
  src/components/FileList/FileElement.js
  src/components/FileList/filelist.css
  src/components/FileUpload/FileUploadTarget.js
  src/components/FileUpload/file-upload.css
  src/components/Login/Login.js
  src/components/NavBar/NavBarButton.js
  src/components/NavBar/navbar.css
  src/components/StudyHeader/StudyHeader.jsx
  src/components/StudyHeader/studyheader.css
  src/components/StudyList/StudyCard.jsx
  src/components/StudyList/StudyList.jsx
  src/components/StudyList/studylist.css
  src/views/AnnotationView.js
  src/views/StudyFilesListView.js
  yarn.lock
Labels: design, ready-for-review, refactor

#203 🤡 Mock UI Kit Icon component
  __mocks__/kf-uikit.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
Labels: refactor

#205 ♻️ Update dev token list from cache
  src/containers/NewTokenFormContainer.js
  src/views/TokensListView.js
Labels: bug, refactor

#206 ♻️ Delete token by name
  src/components/Tokens/TokenList.js
  src/state/mutations.js
  src/views/TokensListView.js
Labels: bug, refactor

#210 ♻️ Delete file from query cache
  src/components/FileList/FileList.js
  src/state/mutations.js
Labels: refactor

#211 ✅ Test file deletion from FileList
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/allStudies.json
  __mocks__/kf-api-study-creator/responses/deleteFile.json
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  package.json
  src/views/StudyFilesListView.test.js
  yarn.lock
Labels: refactor

#212 🐛 Fix icon mocks
  __mocks__/kf-uikit.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
Labels: bug, refactor
