Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-09, with the labels that each got.

#433 ✨ Add button to create first study for admins
  src/views/StudyListView.js
Labels: feature

#432 🔧 Update env schema
  .env.schema
  README.md
Labels: devops, documentation

#435 ♻️ Refactor project list showing unlink button for admin user
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/state/mutations.js
  src/views/CavaticaProjectsView.js
Labels: feature, refactor

#429 ✨ Add modal for link / unlink Cavatica project
  src/App.css
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/StudyInfo.test.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/forms/LinkProjectForm.js
  src/forms/index.js
  src/modals/LinkProjectModal.js
  src/state/queries.js
  src/views/StudyInfoView.js
Labels: feature

#438 ♻️ Reorganize event list
  src/common/enums.js
  src/common/fileUtils.js
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/EventList.test.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
  src/components/StudyInfo/StudyInfo.js
Labels: bug, refactor

#439 ✨ Add view for event history
  src/Routes/index.js
  src/components/EventList/index.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/Header/Header.js
  src/state/queries.js
  src/views/EventsView.js
  src/views/index.js
Labels: feature

#436 ✨ Add option to create which type of Cavatica projects on creating a new study
  src/common/enums.js
  src/forms/NewStudyForm.js
  src/state/mutations.js
  src/views/NewStudyView.js
Labels: feature

#444 🐛 Handle no projects
  src/forms/LinkProjectForm.js
  src/modals/LinkProjectModal.js
Labels: bug

#445 💄 Refactor study info layout
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/views/StudyInfoView.js
Labels: design, refactor

#446 💄 Refactor study edit layout and add more fields
  src/forms/EditStudyForm.js
  src/forms/NewProjectForm.js
  src/forms/NewStudyForm.js
  src/modals/EditStudyModal.js
Labels: design, feature, refactor

#447 ✨ Support markdown for study description
  package.json
  src/App.css
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  yarn.lock
Labels: feature

#453 💄 Display api error message at the bottom of the edit study modal
  src/App.css
  src/modals/EditStudyModal.js
Labels: bug

#454 ♻️ Refactor create project and list project rendering
  src/App.css
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/forms/NewStudyForm.js
  src/modals/NewProjectModal.js
Labels: refactor

#465 ✨ Add Cavatica tab with Cavatica projects and create/link/unlink actions
  src/App.css
  src/Routes/index.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/forms/LinkProjectForm.js
  src/modals/LinkProjectModal.js
  src/views/CavaticaBixView.js
  src/views/index.js
Labels: feature

#466 ♻️ Refactor project button and link rendering
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/state/queries.js
  src/views/CavaticaBixView.js
Labels: refactor

#476 🐛 Allow selection of file type for normal users
  src/views/NewDocumentView.js
Labels: bug

#468 ✨ Add event logs tab view for ADMIN user with type filter and auto refresh
  src/App.css
  src/Routes/index.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/views/LogsView.js
  src/views/index.js
Labels: feature

#473 ♻️ Refactor study list search by adding empty state and make kfId searchable
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
Labels: bug, refactor

#482 🐛 Hide copy button for masked tokens
  src/components/TokenList/TokenList.js
Labels: bug

#461 💄 Re-style input hints for study form
  src/App.css
  src/Routes/index.js
  src/components/StudyList/StudyList.js
  src/forms/EditStudyForm.js
  src/forms/FormField.js
  src/forms/NewStudyForm.js
  src/forms/StudyFormSteps.js
  src/modals/EditStudyModal.js
  src/views/NewStudyView.js
Labels: bug, design, refactor

#486 💄 Add user friendly time formats to TimeAgo on hover
  src/common/dateUtils.js
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/StudyInfo/FileSimpleList.js
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/TokenList/TokenList.js
  src/components/TokenList/__snapshots__/TokenList.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design

#489 ✨ Edit Project modal
  src/common/enums.js
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/forms/EditProjectForm.js
  src/forms/LinkProjectForm.js
  src/forms/index.js
  src/modals/EditProjectModal.js
  src/modals/index.js
  src/state/mutations.js
  src/views/CavaticaProjectsView.js
Labels: feature

#487 ✨ Add step view for study info page with editing mode
  src/App.css
  src/Routes/index.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/StudyInfo.test.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/forms/EditStudyForm.js
  src/forms/FormField.js
  src/forms/NewStudyForm.js
  src/forms/StudyFormSteps.js
  src/forms/index.js
  src/views/NewStudyView.js
  src/views/StudyInfoView.js
Labels: design, feature, refactor

#491 ✨ Feature UserSnap widget
  public/index.html
Labels: feature

#481 💄Re-style Study List Item attributes
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/views/StudyFilesListView.js
  src/views/__tests__/StudyFilesListView.test.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design, refactor, usability improvement

#492 ✨Feature version list item status tooltip
  src/components/VersionList/VersionItem.js
Labels: feature, usability improvement

#458 ✨Updated Document Indicator
  src/App.css
  src/common/fileUtils.js
  src/components/Badge/Badge.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/ListFilterBar/ListFilterBar.js
  src/modals/UploadWizard/UploadWizard.js
  src/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/views/StudyFilesListView.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: feature, usability improvement
