Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-11, with the labels that each got.

#528 📷 Improve Snapshot coverage on views
  .circleci/config.yml
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/allEvents.json
  __mocks__/kf-api-study-creator/responses/allProjects.json
  __mocks__/kf-api-study-creator/responses/allUsers.json
  __mocks__/kf-api-study-creator/responses/createDevToken.json
  __mocks__/kf-api-study-creator/responses/createStudy.json
  __mocks__/kf-api-study-creator/responses/devTokens.json
  __mocks__/kf-api-study-creator/responses/syncProjects.json
  __mocks__/kf-api-study-creator/responses/updateStudy.json
  src/components/Header/__tests__/Header.test.js
  src/components/TokenList/__test__/TokenList.test.js
  src/components/TokenList/__test__/__snapshots__/TokenList.test.js.snap
  src/documents/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/forms/FormField.js
  src/forms/NewTokenForm.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/views/__test__/CallbackView.test.js
  src/views/__test__/CavaticaBixView.test.js
  src/views/__test__/CavaticaProjectsView.test.js
  src/views/__test__/EventsView.test.js
  src/views/__test__/LoginView.test.js
  src/views/__test__/LogsView.test.js
  src/views/__test__/NewStudyView.test.js
  src/views/__test__/ProfileView.test.js
  src/views/__test__/StudyInfoView.test.js
  src/views/__test__/TokenListView.test.js
  src/views/__test__/__snapshots__/CallbackView.test.js.snap
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__test__/__snapshots__/EventsView.test.js.snap
  src/views/__test__/__snapshots__/LoginView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
  src/views/__test__/__snapshots__/ProfileView.test.js.snap
  src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__test__/__snapshots__/TokenListView.test.js.snap
Labels: refactor

#532 ✨ Add UI version number banner to footer
  netlify.toml
  package.json
  src/App.css
  src/Routes/index.js
  src/common/enums.js
  src/components/Footer/Footer.js
  src/components/Footer/__tests__/Footer.test.js
  src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__test__/__snapshots__/EventsView.test.js.snap
  src/views/__test__/__snapshots__/LoginView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
  src/views/__test__/__snapshots__/ProfileView.test.js.snap
  src/views/__test__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__test__/__snapshots__/TokenListView.test.js.snap
Labels: feature

#539 🐛 Fix study subscription table overflow columns in the user profile page
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/containers/StudySubscriptionContainer.js
Labels: bug

#522 🐛 Add back study file list table header
  src/App.css
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/documents/views/StudyFilesListView.js
  src/documents/views/__tests__/StudyFilesListView.test.js
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
Labels: bug

#543 👷 Update QA api to use kidsfirstdrc.org
  netlify.toml
Labels: devops

#541 💄 Add file type description
  src/App.css
  src/common/enums.js
  src/documents/components/FileDetail/SelectElement.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
  src/documents/views/NewDocumentView.js
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  src/views/__test__/__snapshots__/NewStudyView.test.js.snap
Labels: design, refactor

#526 ✨ Remove file upload/edit block from document title validation
  src/App.css
  src/common/globals.js
  src/documents/forms/DocumentTitleValidationIndicators.js
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/ExistingDocsMessage.js
  src/documents/forms/__tests__/EditDocumentFormValidation.test.js
  src/documents/forms/__tests__/ValidationFunction.test.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
  src/documents/forms/validate.js
  src/documents/modals/EditDocumentModal.js
  src/documents/modals/UploadWizard/UploadSteps/DocumentSelectionStep.js
  src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js
  src/documents/modals/UploadWizard/UploadWizard.js
  src/documents/utilities.js
  src/documents/views/NewDocumentView.js
  src/documents/views/__tests__/NewDocumentView.test.js
  src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap
Labels: bug, feature

#545 📝 Update feature request issue template adding "requirements" section
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
