Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-07, with the labels that each got.

#333 💄 Use Semantic for file edit / upload modals
  src/common/fileUtils.js
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
  src/modals/EditDocumentModal.js
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/modals/NewVersionModal/UploadStep.js
  src/modals/VersionInfoModal.js
Labels: design, refactor

#336 💄 Use Semantic for Study List
  __mocks__/kf-api-study-creator/responses/allStudies.json
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/ToggleButtons/ToggleButtons.css
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/ToggleButtons.test.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/state/queries.js
Labels: design, refactor

#318 💄Use Semantic for file list view
  package.json
  src/common/fileUtils.js
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/CopyButton.test.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
  src/components/FileActionButtons/FileActionButtons.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/filelist.css
  src/components/FileUpload/FileUploadTarget.js
  src/components/FileUpload/__snapshots__/FileUploadTarget.test.js.snap
  src/components/Pagination/Pagination.js
  src/components/Pagination/pagination.css
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/containers/UploadContainer.js
  src/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
  src/views/StudyFilesListView.js
  src/views/__tests__/StudyFilesListView.test.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  yarn.lock
Labels: design, refactor

#339 ♻️ Reorganize Header component
  src/Routes/index.js
  src/components/Header/Header.js
  src/components/Header/__tests__/Header.test.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/Header/index.js
  src/components/HeaderButton/HeaderButton.js
Labels: component, refactor

#332 💄 Use Semantic for Study Header
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/StudyHeader/StudyHeader.css
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
  src/components/StudyNavBar.js
  src/views/NavBarView.js
Labels: design, refactor

#345 ✅ Render tests in container
  src/components/Badge/__tests__/Badge.test.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/Modal/__tests__/Modal.test.js
  src/components/Modal/__tests__/__snapshots__/Modal.test.js.snap
Labels: refactor

#344 🔥 Remove unused NotificationBar
  src/components/NotificationBar/NotificationBar.js
  src/components/NotificationBar/notification-bar.css
Labels: refactor

#343 ♻️ Reorganize the StudyNavBar component
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/StudyNavBar.test.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/components/StudyNavBar/index.js
  src/views/NavBarView.js
Labels: refactor

#315 💄 Use Semantic for Profile View
  src/forms/UpdateProfileForm.js
  src/views/ProfileView.js
Labels: design, refactor

#340 💄 Use Semantic for File Detail view
  src/App.css
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/AvatarTimeAgo/__tests__/AvatarTimeAgo.test.js
  src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
  src/components/FileAnnotation/SelectElement.js
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/VersionList/VersionItem.js
  src/components/VersionList/VersionList.js
  src/components/VersionList/_tests_/VersionItem.test.js
  src/components/VersionList/_tests_/VersionList.test.js
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/containers/FileDetailContainer.js
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
  src/modals/VersionInfoModal.js
  src/views/FileDetailView.js
Labels: design, refactor

#346 💄 Usability improvements for FileList
  src/components/CopyButton/CopyButton.js
  src/components/FileActionButtons/FileActionButtons.js
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.css
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/containers/FileActionsContainer.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: refactor

#347 ♻️ Make entire version item row clickable
  src/components/VersionList/VersionItem.js
Labels: refactor

#348 🐛 Handle test errors
  src/components/FileDetail/FileDetail.js
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/forms/NewDocumentForm.js
  src/modals/NewVersionModal/DescriptionStep.js
Labels: bug, refactor

#352 💄 Use Semantic for error message
  src/components/FileUpload/FileUploadTarget.js
  src/components/FileUpload/FileUploadTarget.test.js
  src/components/FileUpload/__snapshots__/FileUploadTarget.test.js.snap
  src/containers/FileDetailContainer.js
  src/modals/NewVersionModal/NewVersionFlow.js
  src/views/NavBarView.js
  src/views/ProfileView.js
  src/views/StudyFilesListView.js
  src/views/StudyListView.js
  src/views/TokensListView.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: component, design, refactor

#362 💄 Semantic refactor for tokens view and profile view
  src/components/Loading/index.js
  src/components/Loading/loading.css
  src/containers/StudySubscriptionContainer.js
  src/forms/NewTokenForm.js
  src/views/ProfileView.js
Labels: design, refactor

#363 💄 Semantic refactor for avatar image component
  src/assets/defaultAvatar.png
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/TokenList/TokenList.js
Labels: bug, refactor

#350 💄 Use Semantic for File Annotation view
  src/App.css
  src/components/FileAnnotation/SelectElement.js
  src/components/FileAnnotation/fileannotation.css
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/forms/EditDocumentForm.js
  src/forms/EditDocumentForm.test.js
  src/forms/NewDocumentForm.js
  src/forms/NewDocumentForm.test.js
  src/forms/__snapshots__/EditDocumentForm.test.js.snap
  src/forms/__snapshots__/NewDocumentForm.test.js.snap
  src/forms/index.js
  src/modals/EditDocumentModal.js
  src/views/NewDocumentView.js
Labels: component, design, refactor

#376 💄 Semantic refactor for study list and file list
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/__tests__/studyByKfId.json
  src/components/StudyList/StudyList.js
  src/containers/StudySubscriptionContainer.js
  src/forms/NewTokenForm.js
  src/forms/UpdateProfileForm.js
  src/modals/VersionInfoModal.js
Labels: bug, refactor

#377 🔥 Remove ui kit dependency
  package.json
  src/components/Modal/Modal.js
  src/components/Modal/ModalFooter.js
  src/components/Modal/ModalHeader.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/Modal/__tests__/__snapshots__/Modal.test.js.snap
  src/components/Modal/modal.css
  src/index.css
  yarn.lock
Labels: refactor

#378 💄 Semantic refactor for study header
  src/App.css
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
Labels: design, refactor

#375 💄 Semantic refactor version list and file detail view
  src/App.css
  src/common/fileUtils.js
  src/components/Badge/__tests__/__snapshots__/Badge.test.js.snap
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/VersionList/VersionItem.js
  src/components/VersionList/VersionList.js
  src/components/VersionList/_tests_/VersionItem.test.js
  src/components/VersionList/_tests_/__snapshots__/VersionItem.test.js.snap
  src/components/VersionList/_tests_/__snapshots__/VersionList.test.js.snap
  src/forms/__snapshots__/EditDocumentForm.test.js.snap
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/VersionInfoModal.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design, refactor

#380 💄Use semantic for empty stage view
  src/views/EmptyView.js
Labels: design, refactor

#382 🔥 Semantic ui style cleanup
  src/App.css
  src/assets/background-science.jpg
  src/assets/icons/icon-box.svg
  src/assets/icons/icon-checkmark.svg
  src/assets/icons/icon-clinical.svg
  src/assets/icons/icon-edit.svg
  src/assets/icons/icon-error.svg
  src/assets/icons/icon-misc.svg
  src/assets/icons/icon-notification.svg
  src/assets/icons/icon-sequencing.svg
  src/assets/icons/icon-upload.svg
  src/assets/icons/index.js
  src/components/Badge/badge.css
  src/components/CopyButton/CopyButton.css
  src/components/CopyButton/CopyButton.js
  src/components/FileActionButtons/FileActionButtons.css
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileDetail/file-detail.css
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.css
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileUpload/file-upload.css
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/Icon/Icon.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/StudyList/studylist.css
  src/components/TokenList/TokenList.js
  src/components/TokenList/__snapshots__/TokenList.test.js.snap
  src/components/VersionList/version-list.css
  src/forms/EditDocumentForm.js
  src/forms/__snapshots__/EditDocumentForm.test.js.snap
  src/index.css
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/NewVersionModal/UploadStep.js
  src/modals/VersionInfoModal.js
  src/views/CallbackView.js
  src/views/LoginView.js
  src/views/StudyFilesListView.js
  src/views/TokensListView.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: refactor

#374 ♻️ Add Token fragment
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/TokensListView.js
Labels: refactor

#372 ♻️ Replace Query component with HOC in navbar
  src/views/NavBarView.js
Labels: refactor

#371 ♻️ Replace Query component with HOC in study list
  src/views/StudyListView.js
Labels: refactor

#369 ♻️ Replace Query component with HOC in study file list
  src/views/StudyFilesListView.js
Labels: refactor

#385 💄 Study File List sort status of changes needed to the top
  src/App.css
  src/common/fileUtils.js
  src/components/Badge/Badge.js
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/VersionList/VersionItem.js
  src/containers/FileDetailContainer.js
  src/modals/NewVersionModal/DescriptionStep.js
  src/modals/VersionInfoModal.js
  src/views/NewDocumentView.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: design, refactor

#388 ♻️ Fragments for study field, file fields, version fields, and creator fields
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  __mocks__/kf-api-study-creator/responses/updateFile.json
  src/components/FileList/__tests__/studyByKfId.json
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
Labels: refactor

#384 📝 Update README file with development and testing section
  README.md
Labels: documentation

#389 ✨ Filter files by approval status/type, sort by created/modified date, and search by file title/description
  src/App.css
  src/common/fileUtils.js
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/__tests__/studyByKfId.json
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: component, feature
