Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-08, with the labels that each got.

#390 ✨ Search study by its name / short name from study list screen
  src/App.css
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
Labels: component, feature

#325 ✨ Feature user roles client state
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/myProfile.json
  src/components/FileDetail/__tests__/EditExistingFile.test.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/FileList/__tests__/FileList.test.js
  src/forms/EditDocumentForm.js
  src/forms/__snapshots__/EditDocumentForm.test.js.snap
  src/modals/EditDocumentModal.js
  src/state/client.js
  src/state/clientSchema.js
  src/state/queries.js
  src/views/ProfileView.js
Labels: feature

#406 💄 Show alternative image when no user profile photo exist
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/Header/Header.js
Labels: component, refactor

#407 💄 Hide filter and search bar on file list when no files exist
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
Labels: component, refactor

#410 ✨ Add drop down for admin functions
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/Header/Header.js
Labels: feature

#412 ✨ Add Cavatica Project list view
  src/Routes/index.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/CavaticaProjectList/index.js
  src/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/components/Header/Header.js
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/CavaticaProjectsView.js
  src/views/index.js
Labels: feature

#403 ✨ Add form page for creating new study
  package.json
  src/Routes/index.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/forms/NewStudyForm.js
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/NewStudyView.js
  src/views/index.js
  yarn.lock
Labels: feature

#413 ✨ Show information about deleted projects
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/views/CavaticaProjectsView.js
Labels: feature, refactor

#414 🐛 Fix new file annotation form by adding user object to it
  src/forms/EditDocumentForm.js
  src/views/NewDocumentView.js
Labels: bug

#416 🐛 Fix new study form date field and Cavatica project study link
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/forms/NewStudyForm.js
Labels: bug

#427 🐛 Don't show studies in profile if the user has none
  src/containers/StudySubscriptionContainer.js
Labels: bug

#426 ✨ Add form for new Cavatica project
  src/common/enums.js
  src/components/StudyInfo/StudyInfo.js
  src/components/StudyInfo/__tests__/__snapshots__/StudyInfo.test.js.snap
  src/forms/NewProjectForm.js
  src/forms/index.js
  src/modals/NewProjectModal.js
  src/state/mutations.js
  src/views/StudyInfoView.js
Labels: feature

#428 🔥 Move role and group resolvers to server
  src/state/client.js
  src/state/clientSchema.js
  src/state/queries.js
Labels: refactor
