Repository kids-first/kf-ui-data-tracker, pull requests merged in 2019-05, with the labels that each got.

#216 ⬆️ Upgrade uikit
  .babelrc
  .circleci/config.yml
  babel.config.js
  jest.config.js
  package.json
  src/App.test.js
  yarn.lock
Labels: devops, refactor

#213 ♻️ Refactor/use grid
  src/App.css
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileAnnotation/fileannotation.css
  src/components/FileList/FileElement.js
  src/components/FileList/filelist.css
  src/components/FileUpload/FileUploadTarget.js
  src/components/FileUpload/file-upload.css
  src/components/Grid/GridContainer.js
  src/components/Grid/grid.css
  src/components/Grid/index.js
  src/components/StudyHeader/StudyHeader.css
  src/components/StudyHeader/StudyHeader.jsx
  src/components/StudyHeader/studyheader.css
  src/components/StudyList/StudyCard.jsx
  src/components/StudyList/StudyList.jsx
  src/components/StudyList/studylist.css
  src/views/AnnotationView.js
  src/views/NavBarView.js
  src/views/StudyFilesListView.js
  src/views/StudyListView.js
Labels: design, ready-for-review, refactor

#197 📷 Add snapshot tests for StudyList
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/allStudies.json
Labels: refactor

#196 📷 Add snapshot tests for StudyHeader
  src/components/StudyHeader/StudyHeader.test.js
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
Labels: refactor

#195 📷 Add snapshot tests for FileUploadTarget
  src/components/FileUpload/FileUploadTarget.test.js
  src/components/FileUpload/__snapshots__/FileUploadTarget.test.js.snap
Labels: refactor

#194 📷 Add snapshot tests for FileList components
  src/components/FileList/FileElement.js
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/__tests__/studyByKfId.json
Labels: refactor

#223 ♻️ Refactor snapshot test data mock
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/FileList.test.js
Labels: refactor

#221 ♻️ Refactor copy button
  src/components/CopyButton/CopyButton.css
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/CopyButton.test.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
Labels: design, refactor

#225 ♻️ Implement SecondaryNav component to navbar
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBarButton.js
  src/components/NavBar/navbar.css
  src/views/NavBarView.js
Labels: design, refactor

#215 ♻️ Refactor studies list
  src/App.css
  src/components/StudyList/StudyGrid.jsx
  src/components/StudyList/StudyList.jsx
  src/components/StudyList/StudyTable.jsx
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/StudyList/studylist.css
  src/components/ToggleButtons/ToggleButtons.css
  src/components/ToggleButtons/ToggleButtons.jsx
  src/components/ToggleButtons/__tests__/ToggleButtons.test.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/state/queries.js
Labels: ready-for-review, refactor

#230 ✅ Functional testing for annotating
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  __mocks__/kf-api-study-creator/responses/updateFile.json
  __mocks__/kf-uikit.js
  __setups__/localStorage.js
  babel.config.js
  jest.config.js
  package.json
  src/App.js
  src/Routes/index.js
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileList/.FileElement.js.swo
  src/components/FileList/FileElement.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/containers/FileEditorContainer.js
  src/views/__tests__/FileUpload.test.js
  src/views/__tests__/StudyFilesListView.test.js
  yarn.lock
Labels: refactor

#218 ♻️ Study File List improvements
  __mocks__/kf-api-study-creator/mocks.js
  src/common/fileUtils.js
  src/components/Badge/Badge.js
  src/components/Badge/badge.css
  src/components/FileActionButtons/FileActionButtons.css
  src/components/FileActionButtons/FileActionButtons.jsx
  src/components/FileList/FileElement.js
  src/components/FileList/FileList.js
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/components/FileList/filelist.css
  src/containers/FileActionsContainer.jsx
  src/views/StudyFilesListView.js
  src/views/__tests__/StudyFilesListView.test.js
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: ready-for-review, refactor

#234 ✅ Global Date.now() mocking
  __setups__/date.js
  jest.config.js
  src/components/FileList/__tests__/FileElement.test.js
  src/components/FileList/__tests__/FileList.test.js
  src/components/StudyHeader/StudyHeader.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: bug, refactor

#235 🐛 Update date compare function
  src/common/fileUtils.js
  src/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: bug

#245 🚑 Fix postcss inheritance
  config-overrides.js
  package.json
  src/App.css
  src/components/Badge/badge.css
  src/components/CopyButton/CopyButton.css
  src/components/FileActionButtons/FileActionButtons.css
  src/components/FileAnnotation/fileannotation.css
  src/components/FileList/filelist.css
  src/components/FileUpload/file-upload.css
  src/components/Modal/Modal.js
  src/components/StudyHeader/StudyHeader.css
  src/components/StudyList/studylist.css
  src/components/ToggleButtons/ToggleButtons.css
  yarn.lock
Labels: bug

#226 ✨ Add file detail view
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  src/Routes/index.js
  src/common/fileUtils.js
  src/components/FileActionButtons/FileActionButtons.jsx
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/VersionItem.js
  src/components/FileDetail/VersionList.js
  src/components/FileDetail/__tests__/VersionItem.test.js
  src/components/FileDetail/__tests__/VersionList.test.js
  src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileDetail/__tests__/fileByKfId.json
  src/components/FileDetail/file-detail.css
  src/components/FileList/FileElement.js
  src/components/NavBar/NavBar.js
  src/containers/DeleteFileMutation.js
  src/containers/FileActionsContainer.jsx
  src/containers/FileDetailContainer.js
  src/containers/FileEditorContainer.js
  src/containers/UploadContainer.js
  src/state/mutations.js
  src/state/queries.js
  src/views/FileDetailView.js
  src/views/__tests__/FileUpload.test.js
  src/views/index.js
Labels: component, design, feature

#248 🐛 Remove duplicate props
  src/components/StudyHeader/StudyHeader.jsx
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
Labels: bug

#249 💄 Align header to page content
  src/App.css
Labels: design

#214 👷 Add bundlesize status check
  .circleci/config.yml
  package.json
Labels: devops

#251 💄 Update file type images to match the design
  __setups__/icons.js
  jest.config.js
  src/assets/icons/box.js
  src/assets/icons/clinical.js
  src/assets/icons/misc.js
  src/assets/icons/sequencing.js
  src/common/fileUtils.js
  src/components/FileAnnotation/FileEditor.js
  src/components/FileAnnotation/SelectElement.js
  src/components/FileAnnotation/__snapshots__/FileEditor.test.js.snap
  src/components/FileAnnotation/fileannotation.css
  src/components/FileDetail/FileDetail.js
  src/components/FileDetail/VersionItem.js
  src/components/FileDetail/__tests__/__snapshots__/VersionItem.test.js.snap
  src/components/FileDetail/__tests__/__snapshots__/VersionList.test.js.snap
  src/components/FileDetail/file-detail.css
Labels: design, refactor

#253 💄Refactor copy button using svg icon as component
  __setups__/icons.js
  src/assets/icons/checkmark.js
  src/components/CopyButton/CopyButton.css
  src/components/CopyButton/CopyButton.js
  src/components/CopyButton/__snapshots__/CopyButton.test.js.snap
Labels: refactor

#254 ✨ Add notification bar component
  __setups__/icons.js
  src/assets/icons/edit.js
  src/assets/icons/notification.js
  src/components/FileDetail/NotificationBar.js
  src/components/FileDetail/file-detail.css
Labels: component

#255 ✨ Add modal component
  package.json
  src/components/Modal/Modal.js
  src/components/Modal/ModalFooter.js
  src/components/Modal/ModalHeader.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/Modal/__tests__/__snapshots__/Modal.test.js.snap
  src/components/Modal/modal.css
  yarn.lock
Labels: component

#261 💄Refactor study header style in grid layout
  src/components/StudyHeader/StudyHeader.css
  src/components/StudyHeader/StudyHeader.jsx
  src/components/StudyHeader/__snapshots__/StudyHeader.test.js.snap
Labels: design, refactor
