Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-11, with the labels that each got.

#924 🏷 Release 0.18.1
  CHANGELOG.md
Labels: release

#923 ✨ Allow users to favorite studies and display ‘favorite studies’ list
  cypress/integration/studies/study_list.spec.js
  src/App.css
  src/common/globals.js
  src/components/StudyList/ActionButtons.js
  src/components/StudyList/Name.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
Labels: feature

#925 ✨ Display colored label for Cavatica project type
  src/App.css
  src/common/enums.js
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/StudyProjects.js
  src/components/StudyInfo/CavaticaCounts.js
Labels: design

#926 ✨ Use markdown for version summary input and display
  src/documents/modals/NewVersionModal/DescriptionStep.js
  src/documents/modals/NewVersionModal/NewVersionFlow.js
  src/documents/modals/NewVersionModal/__tests__/NewVersionFlow.test.js
  src/documents/modals/VersionInfoModal.js
Labels: feature

#928 💄 Update UI design for document detail page
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  src/App.css
  src/documents/components/FileDetail/FileDescription.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileDetailModal.js
  src/documents/components/FileDetail/FileName.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileDetail/Timelines.js
  src/documents/components/FileDetail/VersionCard.js
  src/documents/fragments.js
  src/documents/modals/EditDocumentModal.js
  src/documents/views/FileDetailView.js
Labels: design

#930 🏷 Release 0.18.2
  CHANGELOG.md
Labels: release

#912 ✨ Change releases to study creator backend
  netlify.toml
  src/App.css
  src/common/globals.js
  src/components/ReleaseList/ReleaseList.js
  src/components/ReleaseList/__tests__/ReleaseList.test.js
  src/components/ReleaseList/__tests__/__snapshots__/ReleaseList.test.js.snap
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyList/Release.js
  src/components/StudyList/__tests__/Release.test.js
  src/components/StudyList/__tests__/__snapshots__/Release.test.js.snap
  src/releases/components/ReleaseDetail/Log.js
  src/releases/components/ReleaseDetail/LogViewer.js
  src/releases/components/ReleaseDetail/MarkdownEditor.js
  src/releases/components/ReleaseDetail/ReleaseActions.js
  src/releases/components/ReleaseDetail/ReleaseHeader.js
  src/releases/components/ReleaseDetail/index.js
  src/releases/components/ServiceList/ServiceList.js
  src/releases/components/ServiceSelect/ServiceSelect.js
  src/releases/components/ServiceSelect/index.js
  src/releases/components/StudyTable/StudyTable.js
  src/releases/components/TaskList/TaskList.js
  src/releases/forms/NewReleaseForm.js
  src/releases/fragments.js
  src/releases/mutations.js
  src/releases/queries.js
  src/releases/views/HomeView.js
  src/releases/views/NavigationView.js
  src/releases/views/NewReleaseView.js
  src/releases/views/NewServiceView.js
  src/releases/views/ReleaseDetailView.js
  src/releases/views/ServiceDetailView.js
  src/releases/views/ServicesListView.js
  src/state/client.js
  src/state/queries.js
  src/views/ReleasesView.js
  src/views/StudyListView.js
Labels: feature, refactor
