Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-10, with the labels that each got.

#897 🐛 Fix user group dropdown in user page not updating
  src/admin/views/UsersView.js
Labels: bug

#902 🔧 Add dev/QA amplitude key to netlify builds
  netlify.toml
Labels: devops

#901 ♻️ Default showing only my studies to be false
  cypress/integration/studies/add_study.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studies/study_statuses.spec.js
  src/components/StudyList/StudyList.js
Labels: refactor

#900 ✨ Add copy download url button and copy version kf ID button
  src/App.css
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/VersionList/VersionItem.js
  src/documents/components/VersionList/__tests__/VersionItem.test.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
Labels: feature

#881 ✨ Add document recent events as timeline to document detail page
  __mocks__/kf-api-study-creator/mocks.js
  src/App.css
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/Timelines.js
  src/documents/modals/EditDocumentModal.js
  src/documents/modals/NewVersionModal/NewVersionFlow.js
  src/documents/views/FileDetailView.js
  src/state/queries.js
Labels: feature

#898 ✨ Add services list view and register new service view to release sub app
  src/releases/components/ServiceList/ServiceList.js
  src/releases/components/ServiceList/index.js
  src/releases/components/helpers/NewServiceHelp.js
  src/releases/components/helpers/ServicesHelp.js
  src/releases/components/helpers/index.js
  src/releases/forms/NewServiceForm.js
  src/releases/fragments.js
  src/releases/mutations.js
  src/releases/queries.js
  src/releases/routes.js
  src/releases/views/NavigationView.js
  src/releases/views/NewServiceView.js
  src/releases/views/ServicesListView.js
  src/releases/views/index.js
Labels: feature

#906 ✨ Update run new release flow with confirm widow
  src/App.css
  src/releases/forms/NewReleaseForm.js
  src/releases/views/NewReleaseView.js
Labels: feature

#904 ✨ Add release detail view to release sub app feature
  src/assets/paragraph.png
  src/releases/components/Events/Events.js
  src/releases/components/Events/index.js
  src/releases/components/Progress/Progress.js
  src/releases/components/Progress/index.js
  src/releases/components/ReleaseDetail/MarkdownEditor.js
  src/releases/components/ReleaseDetail/ReleaseActions.js
  src/releases/components/ReleaseDetail/ReleaseHeader.js
  src/releases/components/ReleaseDetail/ReleaseNotes.js
  src/releases/components/ReleaseDetail/index.js
  src/releases/components/ReleaseTable/Name.js
  src/releases/components/ReleaseTable/ReleaseTable.js
  src/releases/components/TaskList/TaskList.js
  src/releases/components/TaskList/index.js
  src/releases/mutations.js
  src/releases/queries.js
  src/releases/routes.js
  src/releases/views/ReleaseDetailView.js
  src/releases/views/index.js
Labels: feature

#905 ✨ Add service detail view to release sub app feature
  src/releases/forms/UpdateServiceForm.js
  src/releases/queries.js
  src/releases/routes.js
  src/releases/views/ServiceDetailView.js
  src/releases/views/index.js
Labels: feature

#907 💄 UI updates around releases and services page
  src/App.css
  src/releases/routes.js
  src/releases/views/HomeView.js
  src/releases/views/ReleaseDetailView.js
  src/releases/views/ServicesListView.js
Labels: design

#908 🏷 Release 0.18.0
  CHANGELOG.md
Labels: release

#909 🔥 Remove status fields from study table
  cypress/integration/studies/study_statuses.spec.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
Labels: design

#910 📈 Add analytics to file actions and file batch actions
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/ListFilterBar/BatchActions.js
  src/documents/components/ListFilterBar/ListFilterBar.js
Labels: refactor

#911 ✨ Add genomic workflow output manifest to file types
  src/common/enums.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Labels: feature

#922 ♻ New release fixes
  src/releases/forms/NewReleaseForm.js
  src/releases/views/NewReleaseView.js
Labels: refactor

#913 👷‍♂️ Use netlify production as qa
  .circleci/config.yml
  netlify.toml
Labels: devops

#914 🐛 Fix markdown editor codeblock indent conversion
  .circleci/config.yml
  package.json
  src/documents/components/FileDetail/FileDescription.js
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/NewDocumentForm.js
  src/documents/forms/NewVersionForm.js
  src/releases/components/ReleaseDetail/MarkdownEditor.js
  src/releases/forms/NewReleaseForm.js
  yarn.lock
Labels: bug

#903 📝 Update setup steps in README
  README.md
Labels: documentation
