Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-07, with the labels that each got.

#781 📈 Add tracking to document uploads
  src/components/StudyList/StudyList.js
  src/documents/components/VersionList/VersionList.js
  src/documents/modals/NewVersionModal/NewVersionFlow.js
  src/documents/modals/UploadWizard/UploadSteps/ChooseMethodStep.js
  src/documents/modals/UploadWizard/UploadSteps/DocumentSelectionStep.js
  src/documents/modals/UploadWizard/UploadSteps/SuccessStep.js
  src/documents/modals/UploadWizard/UploadSteps/VersionSummaryStep.js
  src/documents/modals/UploadWizard/UploadWizard.js
  src/documents/views/NewDocumentView.js
Labels: feature

#785 🏷 Release 0.15.0
  CHANGELOG.md
  release_maker_cfg.json
Labels: release

#773 ✨ Add collaborator roles
  src/assets/collaborators.svg
  src/common/enums.js
  src/components/CollaboratorsList/CollaboratorItem.js
  src/components/CollaboratorsList/CollaboratorsList.js
  src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap
  src/components/StudyList/ActionButtons.js
  src/documents/components/helpers/CollaboratorsHelp.js
  src/documents/components/helpers/index.js
  src/documents/modals/EditDocumentModal.js
  src/documents/views/NewDocumentView.js
  src/documents/views/StudyFilesListView.js
  src/forms/AddCollaboratorForm.js
  src/forms/InviteCollaboratorForm.js
  src/modals/AddCollaboratorModal.js
  src/modals/CreatingStudyModal.js
  src/state/mutations.js
  src/state/queries.js
  src/views/CavaticaBixView.js
  src/views/CollaboratorsView.js
  src/views/LogsView.js
  src/views/NavBarView.js
  src/views/ReleasesView.js
  src/views/StudyInfoView.js
Labels: feature

#790 🐛 Fix tests
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/invites/invite_user.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  src/components/CollaboratorsList/CollaboratorItem.js
  src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap
  src/views/CollaboratorsView.js
Labels: bug

#788 🏷 Release 0.16.0
  CHANGELOG.md
  package.json
Labels: release

#786 ✨ Add ability to add multiple users at once for email invites
  cypress/integration/invites/invite_user.spec.js
  src/App.css
  src/forms/InviteForm.js
  src/modals/InviteModal.js
Labels: feature

#787 💄 Refactor UI for document detail page
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/VersionList/VersionItem.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
  src/documents/components/helpers/BaseHelper.js
Labels: design, refactor

#803 ♻️ Accept permission for investigator to edit document meta
  cypress/integration/documents/document_detail.spec.js
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/__tests__/EditDocumentForm.test.js
  src/documents/modals/EditDocumentModal.js
  src/documents/views/FileDetailView.js
  src/documents/views/StudyFilesListView.js
Labels: refactor

#810 💄 Add user's email to user drop down
  src/forms/AddCollaboratorForm.js
Labels: refactor, usability improvement

#814 🐛 Fix misspelled event description
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
Labels: bug

#817 ✨ Add status for slack channel on study creation modal
  src/modals/CreatingStudyModal.js
Labels: feature

#816 ♻️ Only call updateFile mutation from edit file modal if has changes
  src/documents/modals/EditDocumentModal.js
Labels: refactor

#815 ✨ Support search documents by KF ID
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/views/StudyFilesListView.js
Labels: refactor
