Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-05, with the labels that each got.

#686 🐛 Add coordinator to compose
  .circleci/config.yml
  docker-compose.yml
Labels: bug, devops

#688 🐛 Use correct address for coordinator
  cypress/integration/studyInfo/release.spec.js
  docker-compose.yml
Labels: bug, devops

#680 🔒 Check for permissions on study related tabs
  .circleci/config.yml
  cypress/integration/studyInfo/basic_info.spec.js
  cypress/integration/studyInfo/cavatica.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  cypress/integration/studyInfo/logs.spec.js
  cypress/integration/studyInfo/release.spec.js
  docker-compose.yml
  src/common/notificationUtils.js
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/StudyProjects.js
  src/components/EventList/EventList.js
  src/components/Header/DevHeader.js
  src/components/StudyList/ColumnSelector.js
  src/forms/AddCollaboratorForm.js
  src/forms/FormField.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/ExternalStep.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/forms/StudyInfoForm/Steps/LogisticsStep.js
  src/modals/EditProjectModal.js
  src/modals/LinkProjectModal.js
  src/views/CavaticaBixView.js
  src/views/LogsView.js
  src/views/NavBarView.js
  src/views/ReleasesView.js
  src/views/StudyInfoView.js
Labels: feature

#696 ✨ Full width study table toggle
  cypress/integration/studies/study_list.spec.js
  src/components/StudyList/StudyList.js
Labels: design, feature

#685 ✨ Add sequencing status selector
  cypress/integration/studies/study_statuses.spec.js
  src/components/StudyList/ActionButtons.js
  src/components/StudyList/KfId.js
  src/components/StudyList/Name.js
  src/components/StudyList/Release.js
  src/components/StudyList/SequencingStatus.js
  src/components/StudyList/StatusSelector.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/Release.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/state/fragments.js
  src/state/mutations.js
Labels: component, design, feature

#697 ✨ Persist show only my studies state
  cypress/integration/studies/add_study.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studies/study_statuses.spec.js
  src/components/StudyList/Name.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
Labels: feature

#698 🐛 Fix version sorting
  .circleci/config.yml
  cypress/integration/studies/study_statuses.spec.js
  src/common/__tests__/sortUtils.test.js
  src/common/sortUtils.js
  src/components/StudyList/StudyTable.js
Labels: bug

#699 ✨ Add ingestion status and phenotype status to study table
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/studies/study_statuses.spec.js
  src/components/StudyList/IngestionStatus.js
  src/components/StudyList/PhenotypeStatus.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/state/fragments.js
  src/state/mutations.js
Labels: feature

#701 ✨ Persist study list column sort state
  cypress/integration/studies/study_list.spec.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/containers/StudySubscriptionContainer.js
Labels: feature

#702 🔥 Remove study grid look form study list view
  cypress/integration/studies/study_list.spec.js
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/research/views/ResearchStudyListView.js
  src/state/queries.js
Labels: refactor

#704 ✨ Add hover state to component with descriptive information
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
  src/documents/components/FileList/FileElement.js
  src/state/fragments.js
Labels: feature, refactor

#707 ✨ Display collaborators full name
  cypress/integration/studyInfo/collaborators.spec.js
  src/admin/components/UserList/UserItem.js
  src/common/notificationUtils.js
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/CollaboratorsList/CollaboratorItem.js
  src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap
  src/components/StudyList/Name.js
  src/forms/AddCollaboratorForm.js
Labels: refactor

#710 ♻️ Turn download links into a tags
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
Labels: refactor

#713 ✨ Document list sorting restyle
  .circleci/config.yml
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  src/common/globals.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/views/StudyFilesListView.js
Labels: design, feature, refactor, usability improvement

#714 ✨ Add welcome view
  cypress/integration/studies/study_list.spec.js
  src/assets/welcome.svg
  src/routes/index.js
  src/views/StudyListView.js
  src/views/WelcomeView.js
  src/views/index.js
Labels: feature

#716 ✨ Add help message for documents
  cypress/integration/documents/document_list.spec.js
  src/App.css
  src/assets/add_file.svg
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/documents/components/helpers/BaseHelper.js
  src/documents/components/helpers/DocumentListHelp.js
  src/documents/components/helpers/index.js
  src/views/NavBarView.js
Labels: feature

#715 ✨ Restyle study header
  package.json
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyHeader/__test__/StudyHeader.test.js
  src/components/StudyHeader/__test__/__snapshots__/StudyHeader.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/views/NavBarView.js
  yarn.lock
Labels: design, refactor

#712 ✨ Invite collaborators
  .circleci/config.yml
  cypress/integration/documents/document_list.spec.js
  cypress/integration/navigation/invite_user.spec.js
  cypress/integration/studies/add_collaborator.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  docker-compose.yml
  docker.env
  src/App.css
  src/components/Header/Header.js
  src/components/StudyList/ActionButtons.js
  src/components/StudySelector/StudySelector.js
  src/components/StudySelector/index.js
  src/forms/AddCollaboratorForm.js
  src/forms/InviteCollaboratorForm.js
  src/forms/InviteForm.js
  src/forms/index.js
  src/modals/AddCollaboratorModal.js
  src/modals/InviteModal.js
  src/state/mutations.js
Labels: design, feature, refactor, usability improvement

#720 🐛 Manually log page views
  src/routes/TrackedRoute.js
Labels: bug

#721 ✨ Add slack notify checkbox on study info page
  src/components/StudyHeader/StudyHeader.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/state/fragments.js
  src/views/StudyInfoView.js
Labels: feature

#722 📈 Enrich profile properties for analytics
  src/analyticsTracking/AmplitudeUser.js
  src/components/Header/Header.js
Labels: feature, refactor

#724 ✨ Add icons for new event types
  src/common/enums.js
  src/components/StudyHeader/StudyHeader.js
Labels: feature

#725 🐛 Handle no user profile case for setting amplitude properties
  src/analyticsTracking/AmplitudeUser.js
Labels: bug
