Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-03, with the labels that each got.

#609 ✨ Add buckets view
  src/Routes/index.js
  src/admin/queries.js
  src/admin/views/BucketsView.js
  src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/admin/views/__tests__/__snapshots__/UsersView.test.js.snap
  src/admin/views/index.js
  src/components/BucketsList/BucketsList.js
  src/components/BucketsList/__tests__/BucketList.test.js
  src/components/BucketsList/__tests__/__snapshots__/BucketList.test.js.snap
  src/components/BucketsList/index.js
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/index.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/research/views/__tests__/__snapshots__/NewResearchStudyView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/views/__tests__/BucketsView.test.js
  src/views/__tests__/__snapshots__/BucketsView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
Labels: feature

#613 🔥 Remove research studies
  src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/admin/views/__tests__/__snapshots__/UsersView.test.js.snap
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  src/research/views/__tests__/ResearchStudyListView.test.js
  src/research/views/__tests__/__snapshots__/NewResearchStudyView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/views/__tests__/CavaticaBixView.test.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
Labels: refactor

#612 ♻️ Update create study type name
  src/state/mutations.js
Labels: refactor

#615 🐛 Fix new document creation by adding empty tag list
  __mocks__/kf-api-study-creator/mocks.js
  src/documents/views/NewDocumentView.js
  src/documents/views/__tests__/NewDocumentView.test.js
  src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap
Labels: bug

#616 ✨Add collaborators view
  __mocks__/kf-api-study-creator/responses/addCollaborator.json
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  __mocks__/kf-api-study-creator/responses/studyByKfId_event_err.json
  __mocks__/kf-api-study-creator/responses/studyByKfId_no_projects.json
  __mocks__/kf-api-study-creator/responses/studyByKfId_refetch.json
  src/Routes/index.js
  src/components/CollaboratorsList/CollaboratorItem.js
  src/components/CollaboratorsList/CollaboratorsList.js
  src/components/CollaboratorsList/__tests__/CollaboratorsList.test.js
  src/components/CollaboratorsList/__tests__/__snapshots__/CollaboratorsList.test.js.snap
  src/components/CollaboratorsList/index.js
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  src/forms/AddCollaboratorForm.js
  src/forms/index.js
  src/modals/AddCollaboratorModal.js
  src/modals/index.js
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/CollaboratorsView.js
  src/views/__tests__/CollaboratorsView.test.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CollaboratorsView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/index.js
Labels: feature

#621 ✨ Add document preview
  package.json
  src/App.css
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditFileDescription.test.js.snap
  src/documents/components/FilePreview/FilePreview.js
  src/documents/components/FilePreview/__tests__/FilePreview.test.js
  src/documents/components/FilePreview/__tests__/__snapshots__/FilePreview.test.js.snap
  src/documents/components/FilePreview/index.js
  yarn.lock
Labels: feature

#625 📈 Add scope and events to page views
  src/Routes/TrackedRoute.js
  src/Routes/index.js
Labels: feature
