Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-12, with the labels that each got.

#934 ✨ Add file summary modal to file preview page with learn more button
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/VersionCard.js
  src/documents/views/VersionPreviewView.js
Labels: design

#933 🔧 Add developer views
  package.json
  public/voyager.worker.js
  src/App.css
  src/admin/components/Voyager.js
  src/admin/views/GraphiQLView.js
  src/admin/views/ModelExplorerView.js
  src/admin/views/index.js
  src/components/Header/Header.js
  src/routes/index.js
  yarn.lock
Labels: feature

#931 🎨 Revise upload flow
  src/assets/font.svg
  src/assets/selection.svg
  src/documents/components/UploadSteps/ChooseDocumentStep.js
  src/documents/components/UploadSteps/ChooseTypeStep.js
  src/documents/components/UploadSteps/DocumentOrVersionStep.js
  src/documents/components/UploadSteps/EnterDetailsStep.js
  src/documents/components/UploadSteps/VersionDescriptionStep.js
  src/documents/components/UploadSteps/index.js
  src/documents/forms/NewDocumentForm.js
  src/documents/forms/NewUploadForm.js
  src/documents/forms/NewVersionForm.js
  src/documents/views/FileDetailView.js
  src/documents/views/UploadView.js
  src/views/NavBarView.js
Labels: design, refactor

#942 🔥 Remove unused components
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/__test__/CavaticaCounts.test.js
  src/components/StudyInfo/__test__/FileCounts.test.js
  src/components/StudyInfo/__test__/__snapshots__/CavaticaCounts.test.js.snap
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
Labels: refactor

#941 🎨 Release detail restyle
  src/releases/components/ReleaseDetail/Log.js
  src/releases/components/ReleaseDetail/LogViewer.js
  src/releases/components/ReleaseDetail/MarkdownEditor.js
  src/releases/components/ReleaseDetail/ReleaseActions.js
  src/releases/components/ReleaseDetail/ReleaseHeader.js
  src/releases/components/ReleaseHeader/ReleaseHeader.js
  src/releases/components/ReleaseTaskList/ReleaseTaskList.js
  src/releases/components/ReleaseTaskList/index.js
  src/releases/queries.js
  src/releases/views/NavigationView.js
  src/releases/views/ReleaseDetailView.js
Labels: design, refactor
