Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-09, with the labels that each got.

#847 👷 Update CI
  .circleci/config.yml
  netlify.toml
Labels: devops

#849 ♻️ Update FileType enum
  src/documents/forms/NewDocumentForm.js
  src/documents/mutations.js
  src/documents/views/UploadView.js
Labels: refactor

#839 ✨ Add document version preview page
  .circleci/config.yml
  package.json
  src/App.css
  src/components/Header/Header.js
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/ListFilterBar/BatchActions.js
  src/documents/components/VersionList/VersionItem.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
  src/documents/views/VersionPreviewView.js
  src/documents/views/index.js
  src/routes/index.js
  src/views/NavBarView.js
  yarn.lock
Labels: feature

#850 👷 Add individual workflow for deployment
  .circleci/config.yml
Labels: devops

#852 💄 Add icons for file analysis and version meta permissions
  .circleci/config.yml
  src/common/enums.js
Labels: design

#853 ✨ Expedited types
  src/App.css
  src/assets/document_choice.svg
  src/common/enums.js
  src/documents/forms/NewDocumentForm.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
  src/documents/modals/EditDocumentModal.js
  src/documents/mutations.js
  src/documents/views/UploadView.js
Labels: feature

#860 🎨 Move summary section below versions
  src/documents/components/FileDetail/FileDetail.js
Labels: design

#861 ✨ Add document extract config modal to preview and download config file
  cypress/integration/documents/document_config.spec.js
  package.json
  src/common/enums.js
  src/components/CopyButton/CopyButton.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileDetailModal.js
  src/documents/modals/ExtractConfigModal.js
  src/documents/modals/index.js
  src/documents/views/FileDetailView.js
  yarn.lock
Labels: feature

#858 👷 Deploy production to cloudfront
  .circleci/config.yml
  netlify.toml
Labels: devops

#862 ⚡ Pare down fields requested for all studies
  cypress/integration/invites/invite_user.spec.js
  src/admin/queries.js
  src/admin/views/UsersView.js
  src/common/notificationUtils.js
  src/components/StudyList/IngestionStatus.js
  src/components/StudyList/PhenotypeStatus.js
  src/components/StudyList/SequencingStatus.js
  src/state/fragments.js
  src/state/queries.js
Labels: refactor

#874 ♻️ Refactor preview table for sorting and reducing bundle size
  src/documents/components/PreviewTable/PreviewTable.js
  src/documents/views/VersionPreviewView.js
Labels: feature, refactor

#876 ✨ Warn before exit
  src/assets/form.svg
  src/documents/views/UploadView.js
Labels: feature

#877 ✨ Disable the file type selection option if file is not qualified
  .circleci/config.yml
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/__tests__/EditDocumentForm.test.js
  src/documents/fragments.js
  src/documents/modals/EditDocumentModal.js
Labels: refactor

#875 ✨ New expedited types
  src/common/enums.js
  src/documents/forms/NewDocumentForm.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Labels: feature

#879 🔧 Update QA api url
  netlify.toml
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
Labels: devops

#883 🏷 Release 0.17.0
  CHANGELOG.md
Labels: release

#882 🔥 Remove obsolete new document view and /new-document route
  src/documents/forms/__tests__/EditDocumentFormValidation.test.js
  src/documents/routes.js
  src/documents/views/NewDocumentView.js
  src/documents/views/index.js
  src/routes/index.js
Labels: refactor

#885 ⬆️ Bump node image version
  .circleci/config.yml
Labels: devops

#884 🐛 Fix delete file from file detail page refetch query variable
  src/documents/components/FileDetail/AnalysisSummary.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/forms/NewDocumentForm.js
  src/documents/views/FileDetailView.js
  src/documents/views/UploadView.js
Labels: bug

#886 🏷 Release 0.17.1
  CHANGELOG.md
Labels: release

#893 🔧 Redirect host
  netlify.toml
  src/App.js
  src/common/globals.js
Labels: devops

#894 🏷 Release 0.17.2
  CHANGELOG.md
Labels: release

#873 ✨ Add Releases sub application
  package.json
  src/assets/releases.svg
  src/common/sortUtils.js
  src/components/BaseHelper.js
  src/components/Header/Header.js
  src/documents/components/helpers/CollaboratorsHelp.js
  src/documents/components/helpers/DocumentDetailHelp.js
  src/documents/components/helpers/DocumentListHelp.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
  src/releases/components/ReleaseHeader/ReleaseHeader.js
  src/releases/components/ReleaseHeader/index.js
  src/releases/components/ReleaseTable/CreatedAt.js
  src/releases/components/ReleaseTable/Name.js
  src/releases/components/ReleaseTable/ReleaseTable.js
  src/releases/components/ReleaseTable/Version.js
  src/releases/components/ReleaseTable/index.js
  src/releases/components/StudyTable/StudyTable.js
  src/releases/components/StudyTable/index.js
  src/releases/components/helpers/ReleasesHelp.js
  src/releases/components/helpers/index.js
  src/releases/forms/NewReleaseForm.js
  src/releases/fragments.js
  src/releases/mutations.js
  src/releases/queries.js
  src/releases/routes.js
  src/releases/views/HomeView.js
  src/releases/views/NavigationView.js
  src/releases/views/NewReleaseView.js
  src/releases/views/index.js
  src/routes/index.js
  yarn.lock
Labels: feature
