Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-06, with the labels that each got.

#726 🐛 Defensively check for localStore attributes
  src/analyticsTracking/AmplitudeUser.js
Labels: bug

#723 ✨ Add token exchange view
  cypress/integration/invites/invite_user.spec.js
  cypress/integration/invites/join.spec.js
  package.json
  src/assets/added.svg
  src/routes/index.js
  src/state/mutations.js
  src/views/InviteView.js
  src/views/NotFoundView.js
  src/views/index.js
  yarn.lock
Labels: feature

#727 🖼 Add logo for emails
  public/data_tracker_email.png
Labels: feature

#728 🐛 Include token when logging users into invite view
  src/views/InviteView.js
Labels: bug

#729 🐛 Check expiration time for token validation
  src/views/InviteView.js
Labels: bug

#730 🏷 Release 0.14.0
  CHANGELOG.md
  package.json
Labels: release

#734 🐛 Fix unique key error on study and configuration tables
  src/admin/views/ConfigurationView.js
  src/components/StudyList/StudyTable.js
Labels: bug

#733 ✨ Allow slack channel to be updated
  src/App.css
  src/components/StudyHeader/StudyHeader.js
  src/views/NavBarView.js
Labels: feature

#735 🐛 Fix study header and document loading error
  src/components/StudyHeader/StudyHeader.js
  src/documents/components/FileList/FileElement.js
Labels: bug

#737 🏷 Release 0.14.1
  CHANGELOG.md
Labels: release

#738 ✨ Add preview for user group permissions in users screen
  cypress/integration/invites/invite_user.spec.js
  src/admin/components/UserList/PermissionGroup.js
  src/admin/components/UserList/index.js
  src/admin/views/UsersView.js
  src/common/enums.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
  src/forms/InviteForm.js
  src/modals/InviteModal.js
  src/state/queries.js
Labels: feature

#743 📝 Update issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#747 ♻️ Always display bulk document actions
  cypress/integration/documents/document_list.spec.js
  src/App.css
  src/documents/components/ListFilterBar/BatchActions.js
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/components/helpers/BaseHelper.js
  src/documents/views/StudyFilesListView.js
Labels: refactor

#753 ✨ Add missing fields to configuration page
  src/admin/views/ConfigurationView.js
  src/state/queries.js
Labels: refactor

#754 ✨ Include referrals in tracked routes
  src/routes/TrackedRoute.js
Labels: feature

#755 🏷 Release 0.14.3
  .github/workflows/gh_release.yml
  CHANGELOG.md
Labels: release

#763 🐛 Fix document sorting by last updated date
  cypress/integration/documents/document_list.spec.js
  src/documents/components/FileList/FileList.js
Labels: bug

#764 ✨ Include slack channel as study column
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/slack-update.spec.js
  src/App.css
  src/components/StudyHeader/StudyHeader.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
Labels: feature

#765 ✨ Make study link dropdown searchable
  src/forms/LinkStudyForm.js
Labels: refactor

#766 🔥 Remove approval status from documents
  cypress/integration/documents/document_detail.spec.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileList/FileList.js
  src/documents/components/VersionList/VersionItem.js
  src/documents/components/VersionList/__tests__/VersionItem.test.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
Labels: refactor

#767 ♻️ Disable submit button after creating a study
  src/forms/StudyInfoForm/NewStudyForm.js
  src/views/NewStudyView.js
Labels: refactor

#769 🔥 Remove default document tag options
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/views/FileDetailView.js
  src/documents/views/StudyFilesListView.js
Labels: refactor

#772 💄 Render different document help message on file list and detail
  src/assets/versioning.png
  src/documents/components/helpers/BaseHelper.js
  src/documents/components/helpers/DocumentDetailHelp.js
  src/documents/components/helpers/DocumentListHelp.js
  src/documents/components/helpers/index.js
  src/views/NavBarView.js
Labels: refactor

#771 🔥 Remove default Cavatica projects for new studies
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/forms/StudyInfoForm/Steps/LogisticsStep.js
Labels: refactor

#778 🐛 Fix study table sorting error on expected samples column
  src/components/StudyList/StudyTable.js
Labels: bug

#774 ✨ Set Cavatica workflow type selection with type, method and sample type
  cypress/integration/studyInfo/cavatica.spec.js
  src/common/enums.js
  src/forms/EditProjectForm.js
  src/modals/CreatingStudyModal.js
  src/modals/EditProjectModal.js
  src/views/CavaticaBixView.js
Labels: feature

#779 ♻️ Update study list to use cache-and-network policy
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/views/StudyListView.js
Labels: refactor, usability improvement

#775 ✨ Add admin screen for pending invites
  cypress/integration/invites/invite_user.spec.js
  src/App.css
  src/admin/queries.js
  src/admin/views/PendingInvitesView.js
  src/admin/views/index.js
  src/components/Header/Header.js
  src/components/StudyHeader/StudyHeader.js
  src/routes/index.js
Labels: feature
