Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-08, with the labels that each got.

#819 ✨ Add checkbox in filter bar to show hide file ID column on file table
  cypress/integration/documents/document_list.spec.js
  src/components/StudyList/KfId.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/views/StudyFilesListView.js
Labels: feature

#832 ♻️ Use display name on user list, events, and collaborators
  __mocks__/kf-api-study-creator/responses/allStudies.json
  __mocks__/kf-api-study-creator/responses/devTokens.json
  __mocks__/kf-api-study-creator/responses/fileByKfId.json
  __mocks__/kf-api-study-creator/responses/myProfile.json
  __mocks__/kf-api-study-creator/responses/studyByKfId.json
  cypress/integration/invites/invite_user.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  src/App.css
  src/admin/components/TokenList/TokenList.js
  src/admin/components/UserList/UserItem.js
  src/admin/fragments.js
  src/admin/views/EventsView.js
  src/admin/views/PendingInvitesView.js
  src/admin/views/UsersView.js
  src/common/notificationUtils.js
  src/components/AvatarTimeAgo/AvatarTimeAgo.js
  src/components/AvatarTimeAgo/__tests__/AvatarTimeAgo.test.js
  src/components/AvatarTimeAgo/__tests__/__snapshots__/AvatarTimeAgo.test.js.snap
  src/components/CollaboratorsList/CollaboratorItem.js
  src/components/CollaboratorsList/__tests__/CollaboratorsList.test.js
  src/components/StudyList/Name.js
  src/components/StudyList/StudyList.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionItem.test.js.snap
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
  src/forms/AddCollaboratorForm.js
  src/state/fragments.js
  src/state/queries.js
  src/views/ProfileView.js
Labels: refactor

#825 ✨ Add multi-selection for tag filter with untagged option
  src/App.css
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/views/StudyFilesListView.js
Labels: feature

#822 💄 Revise error message for studies list
  src/assets/bug.svg
  src/components/ImageMessage/ImageMessage.js
  src/components/ImageMessage/index.js
  src/views/StudyListView.js
  src/views/WelcomeView.js
Labels: refactor, usability improvement

#834 🏷 Release 0.16.1
  CHANGELOG.md
Labels: release

#836 🔥 Remove new document title and file name similarity checking
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/ExistingDocsMessage.js
  src/documents/forms/__tests__/ValidationFunction.test.js
  src/documents/forms/validate.js
Labels: refactor

#833 ✨ Add analysis summary to file detail
  src/documents/components/FileDetail/AnalysisSummary.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/queries.js
Labels: design, feature

#838 🐛 Wait for queries before building fragments
  src/admin/views/ConfigurationView.js
Labels: bug

#841 🎨 Add background to study header
  src/App.css
  src/components/StudyHeader/StudyHeader.js
  src/views/NavBarView.js
Labels: design

#840 ♻️ New document upload flow
  cypress/integration/studies/study_list.spec.js
  src/common/urls.js
  src/documents/components/FileDetail/AnalysisSummary.js
  src/documents/components/VersionList/VersionItem.js
  src/documents/forms/NewDocumentForm.js
  src/documents/forms/NewVersionForm.js
  src/documents/mutations.js
  src/documents/routes.js
  src/documents/views/FileDetailView.js
  src/documents/views/StudyFilesListView.js
  src/documents/views/UploadView.js
  src/documents/views/index.js
  src/routes/index.js
Labels: feature

#842 🏷 Release 0.16.2
  CHANGELOG.md
Labels: release

#844 🐛 Pass correct study object to upload bar
  src/documents/views/UploadView.js
Labels: bug

#843 ♻️ Redirect the upload drop zone to new flow
  src/documents/views/StudyFilesListView.js
Labels: refactor

#845 🏷 Release 0.16.3
  CHANGELOG.md
Labels: release
