Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-02, with the labels that each got.

#573 ♻️ Sort deleted projects to bottom of list
  __mocks__/kf-api-study-creator/responses/allProjects.json
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/views/__test__/__snapshots__/CavaticaProjectsView.test.js.snap
Labels: refactor

#570 ✨ Allow users to specify and name research projects on creation
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/studyByKfId_no_projects.json
  src/forms/EditProjectForm.js
  src/forms/NewProjectForm.js
  src/forms/index.js
  src/modals/EditProjectModal.js
  src/modals/NewProjectModal.js
  src/state/mutations.js
  src/views/CavaticaBixView.js
  src/views/__test__/CavaticaBixView.test.js
  src/views/__test__/__snapshots__/CavaticaBixView.test.js.snap
Labels: feature

#576 ✨ Paginate events list
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/allEvents.json
  __mocks__/kf-api-study-creator/responses/allEvents_20.json
  __mocks__/kf-api-study-creator/responses/allEvents_40.json
  __mocks__/kf-api-study-creator/responses/allEvents_refetch.json
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation.json
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_err.json
  __mocks__/kf-api-study-creator/responses/allEvents_studyCreation_ing.json
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
  src/state/queries.js
  src/views/EventsView.js
  src/views/LogsView.js
  src/views/__test__/EventsView.test.js
  src/views/__test__/LogsView.test.js
  src/views/__test__/__snapshots__/EventsView.test.js.snap
  src/views/__test__/__snapshots__/LogsView.test.js.snap
Labels: feature, refactor

#574 ✨ Add configuration view
  __mocks__/kf-api-study-creator/responses/status.json
  src/Routes/index.js
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/state/queries.js
  src/views/ConfigurationView.js
  src/views/__tests__/ConfigurationView.test.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__tests__/__snapshots__/ConfigurationView.test.js.snap
  src/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/views/index.js
Labels: feature

#581 ♻️ Refactor wording on document related pages
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectItem.test.js.snap
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/FileList/__tests__/FileList.test.js
  src/documents/components/FileList/__tests__/__snapshots__/FileList.test.js.snap
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/components/ListFilterBar/__test__/ListFilterBar.test.js
  src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/documents/containers/UploadContainer.js
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
Labels: refactor

#584 ♻️ Refactor Cavatica project list view
  __mocks__/kf-api-study-creator/responses/allProjects.json
  src/components/CavaticaProjectList/CavaticaProjectItem.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/components/CavaticaProjectList/LinkStudyPopup.js
  src/components/CavaticaProjectList/StudyProjects.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectItem.test.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
  src/components/CavaticaProjectList/__tests__/LinkStudyPopup.test.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectItem.test.js.snap
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/CavaticaProjectList/__tests__/__snapshots__/LinkStudyPopup.test.js.snap
  src/forms/LinkStudyForm.js
  src/forms/index.js
  src/views/CavaticaBixView.js
  src/views/CavaticaProjectsView.js
  src/views/__tests__/CavaticaProjectsView.test.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
Labels: feature, usability improvement

#588 ✨ Create Research Studies UI for study list and new study options
  src/App.css
  src/Routes/index.js
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/__test__/__snapshots__/CavaticaCounts.test.js.snap
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/research/views/ResearchStudyListView.js
  src/research/views/__tests__/ResearchStudyListView.test.js
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/research/views/index.js
  src/views/NewStudySelectionView.js
  src/views/__tests__/CavaticaBixView.test.js
  src/views/__tests__/NewStudyView.test.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
  src/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/views/index.js
Labels: feature

#583 ✨ Add 404 page for invalid url
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/fileByKfId_empty.json
  __mocks__/kf-api-study-creator/responses/studyByKfId_empty.json
  src/Routes/index.js
  src/documents/views/FileDetailView.js
  src/documents/views/StudyFilesListView.js
  src/views/CavaticaBixView.js
  src/views/LogsView.js
  src/views/NotFoundView.js
  src/views/ReleasesView.js
  src/views/StudyInfoView.js
  src/views/__tests__/NotFoundView.test.js
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/index.js
Labels: feature

#595 ♻️ Organize admin pages into admin directory
  __mocks__/kf-api-study-creator/mocks.js
  src/Routes/index.js
  src/admin/components/TokenList/TokenList.js
  src/admin/components/TokenList/__test__/TokenList.test.js
  src/admin/components/TokenList/__test__/__snapshots__/TokenList.test.js.snap
  src/admin/components/TokenList/index.js
  src/admin/forms/NewTokenForm.js
  src/admin/fragments.js
  src/admin/mutations.js
  src/admin/queries.js
  src/admin/views/CavaticaProjectsView.js
  src/admin/views/ConfigurationView.js
  src/admin/views/EventsView.js
  src/admin/views/TokensListView.js
  src/admin/views/__tests__/CavaticaProjectsView.test.js
  src/admin/views/__tests__/ConfigurationView.test.js
  src/admin/views/__tests__/EventsView.test.js
  src/admin/views/__tests__/TokenListView.test.js
  src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/ConfigurationView.test.js.snap
  src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/admin/views/index.js
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/index.js
Labels: refactor

#598 ✨ Add hash for study list reflecting layout option
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/ToggleButtons.test.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/research/views/ResearchStudyListView.js
  src/research/views/__tests__/ResearchStudyListView.test.js
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/views/StudyListView.js
  src/views/__tests__/StudyListView.test.js
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
Labels: feature

#597 ✨ Redirect user to error view when having auth0 error
  src/Routes/index.js
  src/state/auth.js
  src/views/NotFoundView.js
  src/views/__tests__/NotFoundView.test.js
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
Labels: refactor

#596 ♻️ Add settings
  __mocks__/kf-api-study-creator/responses/status.json
  src/admin/views/__tests__/__snapshots__/ConfigurationView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
  src/state/queries.js
Labels: refactor

#599 ✨ Add users view for admin
  __mocks__/kf-api-study-creator/mocks.js
  __mocks__/kf-api-study-creator/responses/allUsers.json
  src/Routes/index.js
  src/admin/views/UsersView.js
  src/admin/views/__tests__/EventsView.test.js
  src/admin/views/__tests__/UsersView.test.js
  src/admin/views/__tests__/__snapshots__/CavaticaProjectsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/EventsView.test.js.snap
  src/admin/views/__tests__/__snapshots__/TokenListView.test.js.snap
  src/admin/views/__tests__/__snapshots__/UsersView.test.js.snap
  src/admin/views/index.js
  src/common/enums.js
  src/components/Header/Header.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/research/views/__tests__/__snapshots__/NewResearchStudyView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyInfoView.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/state/queries.js
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
Labels: feature
