Repository kids-first/kf-ui-data-tracker, pull requests merged in 2020-04, with the labels that each got.

#637 💄 Displaying user who made the last changes on the file
  src/documents/components/FileDetail/FileDetail.js
Labels: refactor

#638 ✨ Add DBG file type for dbGaP Submission File
  src/common/enums.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
  src/documents/views/__tests__/__snapshots__/NewDocumentView.test.js.snap
  src/documents/views/__tests__/__snapshots__/StudyFilesListView.test.js.snap
Labels: feature

#630 ✅ Add end to end tests
  .circleci/config.yml
  Dockerfile
  README.md
  cypress.json
  cypress/Dockerfile
  cypress/integration/navigation/admin_navigation.spec.js
  cypress/integration/navigation/user_navigation.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/package.json
  cypress/support/commands.js
  cypress/support/index.js
  cypress/yarn.lock
  docker-compose.yml
  docker.env
  jest.config.js
  package.json
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/components/ToggleButtons/__tests__/ToggleButtons.test.js
  src/components/ToggleButtons/__tests__/__snapshots__/ToggleButtons.test.js.snap
  src/research/views/__tests__/__snapshots__/ResearchStudyListView.test.js.snap
  src/views/__tests__/BucketsView.test.js
  src/views/__tests__/CallbackView.test.js
  src/views/__tests__/CavaticaBixView.test.js
  src/views/__tests__/CollaboratorsView.test.js
  src/views/__tests__/LoginView.test.js
  src/views/__tests__/LogsView.test.js
  src/views/__tests__/NavBarView.test.js
  src/views/__tests__/NewStudyView.test.js
  src/views/__tests__/NotFoundView.test.js
  src/views/__tests__/ProfileView.test.js
  src/views/__tests__/ReleasesView.test.js
  src/views/__tests__/StudyInfoView.test.js
  src/views/__tests__/StudyListView.test.js
  src/views/__tests__/__snapshots__/BucketsView.test.js.snap
  src/views/__tests__/__snapshots__/CallbackView.test.js.snap
  src/views/__tests__/__snapshots__/CavaticaBixView.test.js.snap
  src/views/__tests__/__snapshots__/CollaboratorsView.test.js.snap
  src/views/__tests__/__snapshots__/LoginView.test.js.snap
  src/views/__tests__/__snapshots__/LogsView.test.js.snap
  src/views/__tests__/__snapshots__/NavBarView.test.js.snap
  src/views/__tests__/__snapshots__/NewStudyView.test.js.snap
  src/views/__tests__/__snapshots__/NotFoundView.test.js.snap
  src/views/__tests__/__snapshots__/ProfileView.test.js.snap
  src/views/__tests__/__snapshots__/ReleasesView.test.js.snap
  src/views/__tests__/__snapshots__/StudyInfoView.test.js.snap
  src/views/__tests__/__snapshots__/StudyListView.test.js.snap
  yarn.lock
Labels: devops

#632 ✨ Allow searching and filtering stuides by collaborators
  src/components/CavaticaProjectList/__tests__/CavaticaProjectItem.test.js
  src/components/CavaticaProjectList/__tests__/CavaticaProjectList.test.js
  src/components/CavaticaProjectList/__tests__/LinkStudyPopup.test.js
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectItem.test.js.snap
  src/components/CavaticaProjectList/__tests__/__snapshots__/CavaticaProjectList.test.js.snap
  src/components/CavaticaProjectList/__tests__/__snapshots__/LinkStudyPopup.test.js.snap
  src/components/Header/__tests__/Header.test.js
  src/components/Header/__tests__/__snapshots__/Header.test.js.snap
  src/components/StudyList/StudyList.js
  src/components/StudyList/__tests__/StudyList.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyList.test.js.snap
  src/components/ToggleButtons/ToggleButtons.js
  src/documents/components/FileDetail/__tests__/EditExistingFile.test.js
  src/documents/components/FileDetail/__tests__/EditFileDescription.test.js
  src/documents/components/FileDetail/__tests__/__snapshots__/EditExistingFile.test.js.snap
  src/documents/components/FileDetail/__tests__/__snapshots__/EditFileDescription.test.js.snap
  src/documents/components/ListFilterBar/__test__/ListFilterBar.test.js
  src/documents/components/ListFilterBar/__test__/__snapshots__/ListFilterBar.test.js.snap
  src/documents/modals/UploadWizard/__tests__/UploadWizard.test.js
  src/documents/modals/UploadWizard/__tests__/__snapshots__/UploadWizard.test.js.snap
  src/state/queries.js
  src/views/StudyListView.js
Labels: feature

#643 📝 Update the bug template for issues
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: refactor

#636 ✨ Hyperlink IDs in event logs feature
  src/common/enums.js
  src/components/EventList/EventList.js
  src/components/EventList/__tests__/__snapshots__/EventList.test.js.snap
Labels: feature

#645 🐛 Log users out of Auth0
  netlify.toml
  src/common/globals.js
  src/state/auth.js
Labels: bug

#646 ♻️ Check permissions for admin dropdown
  src/common/__tests__/permissions.test.js
  src/common/permissions.js
  src/components/Header/Header.js
Labels: bug

#639 ♻️ Auto focus add tag dropdown input on open
  src/common/enums.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/views/StudyFilesListView.js
Labels: refactor

#657 🐛 Hide collaborators column
  src/containers/StudySubscriptionContainer.js
Labels: bug

#669 ✅ Add test coverage for integration tests
  .circleci/config.yml
  cypress/integration/navigation/admin_navigation.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  package.json
  src/components/Header/Header.js
  yarn.lock
Labels: devops

#667 User groups tests
  .circleci/config.yml
  cypress/integration/navigation/admin_navigation.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  jest.config.js
  package.json
  src/components/Header/Header.js
  yarn.lock
Labels: devops

#666 📝 Update PR template
  .github/pull_request_template.md
Labels: documentation

#659 🔒 Check for permissions on collaborator tab
  src/views/CollaboratorsView.js
Labels: bug

#660 🔒 Restricted routes
  src/App.js
  src/common/__tests__/permissions.test.js
  src/common/permissions.js
  src/documents/routes.js
  src/routes/AdminRoute.js
  src/routes/PrivateRoute.js
  src/routes/RestrictedRoute.js
  src/routes/TrackedRoute.js
  src/routes/index.js
Labels: feature

#661 🔒 Protect events
  src/routes/index.js
Labels: feature

#662 🔒 Protect users view
  src/routes/index.js
Labels: feature

#663 🔒 Protect configuration view
  src/routes/index.js
Labels: feature

#664 🔒 Protect buckets
  src/routes/index.js
Labels: feature

#665 🔒 Protect tokens
  src/routes/index.js
Labels: feature

#676 🙈 Update .gitignore with test files
  .gitignore
Labels: refactor

#673 ✨ Add developer toolbar
  src/App.js
  src/common/globals.js
  src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/components/Header/DevHeader.js
  src/components/Header/Header.js
  src/state/queries.js
Labels: feature

#670 ✅ Test different user groups
  .circleci/config.yml
  cypress.json
  cypress/integration/navigation/admin_navigation.spec.js
  cypress/integration/navigation/user_navigation.spec.js
  cypress/integration/studies/add_study.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/support/commands.js
  docker-compose.yml
  src/routes/index.js
Labels: feature

#679 🐛 Fix Cypress CI
  .circleci/config.yml
  cypress.json
  cypress/integration/navigation/user_navigation.spec.js
  docker-compose.yml
  docker.env
Labels: bug, devops

#671 🔒 Check for permissions on study list and add study feature
  .circleci/config.yml
  cypress/integration/studies/add_study.spec.js
  src/components/Header/Header.js
  src/components/StudyInfo/CavaticaCounts.js
  src/components/StudyInfo/FileCounts.js
  src/components/StudyInfo/__test__/__snapshots__/CavaticaCounts.test.js.snap
  src/components/StudyInfo/__test__/__snapshots__/FileCounts.test.js.snap
  src/components/StudyList/StudyCard.js
  src/components/StudyList/StudyGrid.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/routes/index.js
  src/views/StudyListView.js
Labels: feature

#678 🎨 Restyle study table
  __mocks__/kf-api-study-creator/responses/allStudies.json
  __mocks__/kf-api-study-creator/responses/myProfile.json
  cypress/integration/studies/study_list.spec.js
  src/App.css
  src/common/globals.js
  src/components/StudyList/ActionButtons.js
  src/components/StudyList/Release.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/ActionButtons.test.js
  src/components/StudyList/__tests__/Release.test.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/Release.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/state/queries.js
  src/views/StudyListView.js
Labels: design, refactor

#672 🔒 Check for permissions in document list and document detail
  cypress/integration/documents/document_list.spec.js
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileActionButtons/__tests__/__snapshots__/FileActionButtons.test.js.snap
  src/documents/components/FileDetail/FileDescription.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileDetailModal.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/VersionList/VersionList.js
  src/documents/components/VersionList/__tests__/__snapshots__/VersionList.test.js.snap
  src/documents/forms/EditDocumentForm.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/modals/EditDocumentModal.js
  src/documents/modals/UploadWizard/UploadSteps/ChooseMethodStep.js
  src/documents/modals/UploadWizard/UploadWizard.js
  src/documents/modals/VersionInfoModal.js
  src/documents/views/FileDetailView.js
  src/documents/views/NewDocumentView.js
  src/documents/views/StudyFilesListView.js
Labels: feature

#684 ✅ Adjust document list test based on mock data
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
Labels: refactor

#683 ✨ Select study list columns
  src/components/StudyList/ColumnSelector.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/StudyTable.test.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/containers/StudySubscriptionContainer.js
Labels: design, feature
