Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-07, with the labels that each got.

#1004 ✨ Add data validation page for internal data review with validation report
  src/App.css
  src/documents/components/DataValidation/DataValidation.js
  src/documents/components/ReviewDetail/ReviewDetail.js
  src/documents/components/helpers/DataValidationHelp.js
  src/documents/components/helpers/index.js
  src/documents/views/DataValidationView.js
  src/documents/views/ReviewDetailView.js
  src/documents/views/ReviewListView.js
  src/documents/views/index.js
  src/routes/index.js
  src/state/fragments.js
  src/state/mutations.js
  src/state/queries.js
  src/views/NavBarView.js
Labels: feature

#1030 ✨ Update document types to match templates
  src/common/enums.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/SelectElement.js
  src/documents/components/FileFolder/FileSimpleElement.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/__tests__/__snapshots__/FileElement.test.js.snap
  src/documents/components/ReviewFiles/ReviewFileElement.js
  src/documents/components/UploadSteps/ChooseTypeStep.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Labels: feature

#1064 ✨ Add organizations features
  cypress/fixtures/example.json
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  cypress/integration/studies/add_study.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  cypress/integration/studyInfo/logs.spec.js
  src/admin/components/OrganizationList/OrganizationItem.js
  src/admin/components/OrganizationList/OrganizationList.js
  src/admin/components/OrganizationList/index.js
  src/admin/forms/EditOrganizationForm.js
  src/admin/fragments.js
  src/admin/mutations.js
  src/admin/queries.js
  src/admin/views/OrganizationsView.js
  src/admin/views/index.js
  src/components/Header/Header.js
  src/components/StudyList/ActionButtons.js
  src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/modals/AddCollaboratorModal.js
  src/modals/InviteModal.js
  src/routes/index.js
  src/state/queries.js
  src/views/NewStudyView.js
  src/views/StudyListView.js
Labels: feature

#1065 ✨ Add feature allows user to transfer study to another organization
  src/components/Header/Header.js
  src/components/StudyList/ActionButtons.js
  src/modals/TransferStudyModal.js
  src/state/mutations.js
  src/state/queries.js
Labels: feature

#1066 ✨ Add feature allows user to add or remove member of an organization
  src/App.css
  src/admin/components/UserList/UserItem.js
  src/admin/components/UserList/UserList.js
  src/admin/queries.js
  src/admin/views/UsersView.js
  src/state/mutations.js
Labels: feature

#1075 🏷 Release 0.21.0
  CHANGELOG.md
Labels: release

#1077 ♻️ Replace static site orb with s3 orb
  .circleci/config.yml
Labels: devops

#1079 ♻️ Reduce required cols in file types to match backend
  src/common/enums.js
  src/documents/forms/__tests__/__snapshots__/EditDocumentForm.test.js.snap
  src/documents/forms/__tests__/__snapshots__/EditDocumentFormValidation.test.js.snap
Labels: refactor

#1081 ✨ Set document type groups for review
  src/documents/components/ReviewDetail/ReviewVersions.js
Labels: feature

#1080 🏷 Release 0.21.1
  CHANGELOG.md
Labels: release
