Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-09, with the labels that each got.

#1113 ♻️ Refactor study document tab layout and refetch
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileUpload/FileUploadTarget.js
  src/documents/components/FileUpload/__test__/__snapshots__/FileUploadTarget.test.js.snap
  src/documents/components/ListFilterBar/BatchActions.js
  src/documents/views/StudyFilesListView.js
Labels: refactor

#1115 🏷 Release 0.23.1
  CHANGELOG.md
Labels: release

#1118 🐛 Fix view only template missing function error on close
  src/documents/components/UploadSteps/ChooseTypeStep.js
  src/modals/DataTemplateEditModal.js
Labels: bug

#1120 💄Change StudyNavBar Logs button to Events
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/routes/index.js
Labels: design

#1122 🏷 Release 0.23.2
  CHANGELOG.md
Labels: release

#1127 🐛 Fix release log content cut off error
  src/releases/components/ReleaseDetail/Log.js
  src/releases/components/ReleaseDetail/LogViewer.js
Labels: bug

#1129 🏷 Release 0.23.3
  CHANGELOG.md
Labels: release
