Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-04, with the labels that each got.

#1011 🔥 Remove roles from user fragment
  src/admin/views/CavaticaProjectsView.js
  src/state/fragments.js
Labels: refactor

#1010 💄 Refactor study list sizing and add favorite studies search
  cypress/integration/studies/study_list.spec.js
  src/App.css
  src/components/StudyList/Name.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/forms/StudyInfoForm/NewStudyForm.js
  src/views/StudyInfoView.js
Labels: refactor

#1012 🏷 Release 0.20.0
  CHANGELOG.md
Labels: release

#1013 🔥 Remove obsolete research study related views and components
  src/common/notificationUtils.js
  src/components/StudyList/StudyTable.js
  src/components/StudyNavBar/StudyNavBar.js
  src/modals/CreatingStudyModal.js
  src/research/forms/NewResearchStudyForm.js
  src/research/forms/index.js
  src/research/views/NewResearchStudyView.js
  src/research/views/ResearchStudyInfoView.js
  src/research/views/ResearchStudyListView.js
  src/research/views/index.js
  src/routes/AdminRoute.js
  src/routes/index.js
  src/views/NavBarView.js
  src/views/NewStudySelectionView.js
  src/views/index.js
Labels: refactor

#1018 🐛 Fix study nav bar with newly added reviews tab
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
Labels: bug

#1017 💄 Add icons for new release related permission types
  src/admin/components/JobsList/JobsList.js
  src/admin/components/UserList/PermissionGroup.js
  src/common/enums.js
Labels: refactor

#1022 💄 Add icons for data review events and data validation events
  src/common/enums.js
Labels: refactor

#1024 ✨ Add next routes
  .circleci/config.yml
  craco.config.js
  src/@next/routes.tsx
  src/routes/index.js
  src/views/NotFoundView.js
Labels: feature
