Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-03, with the labels that each got.

#995 🔥 Remove unused status fields
  src/components/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/components/Header/DevHeader.js
  src/state/queries.js
Labels: bug, refactor

#996 🏷 Release 0.19.1
  CHANGELOG.md
Labels: release

#997 🐛 Hide devbar if variable not set
  src/components/Header/DevHeader.js
Labels: bug

#998 🏷 Release 0.19.2
  CHANGELOG.md
Labels: release

#976 ✨ Add front-end views for create data review form
  src/assets/data-review.png
  src/common/enums.js
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileFolder/FileFolder.js
  src/documents/components/ListFilterBar/ListFilterBar.js
  src/documents/components/ReviewDetail/ReviewDescription.js
  src/documents/components/ReviewDetail/ReviewDetail.js
  src/documents/components/ReviewDetail/ReviewName.js
  src/documents/components/ReviewDetail/ReviewTimelines.js
  src/documents/components/ReviewDetail/ReviewVersions.js
  src/documents/components/ReviewFiles/ReviewFileElement.js
  src/documents/components/ReviewFiles/ReviewFileList.js
  src/documents/components/ReviewFiles/ReviewFileSection.js
  src/documents/components/helpers/ReviewDetailHelp.js
  src/documents/components/helpers/ReviewListHelp.js
  src/documents/components/helpers/index.js
  src/documents/views/ReviewDetailView.js
  src/documents/views/ReviewListView.js
  src/documents/views/StartReviewView.js
  src/documents/views/StudyFilesListView.js
  src/documents/views/index.js
  src/routes/index.js
  src/state/mutations.js
  src/state/queries.js
  src/views/NavBarView.js
Labels: feature

#1005 ✨ Show confetti when successfully publish the release
  package.json
  src/releases/components/ReleaseDetail/ReleaseActions.js
  yarn.lock
Labels: design
