Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-01, with the labels that each got.

#968 🐛 Don't return exit code for copying artifacts
  .circleci/config.yml
Labels: bug, devops

#948 💄 Increase hit area for releases
  src/releases/components/ReleaseTable/Name.js
  src/releases/components/ReleaseTable/ReleaseTable.js
Labels: refactor

#965 🐛 Fix typo in extract config download code button popup
  src/documents/modals/ExtractConfigModal.js
Labels: bug

#964 🐛 Default path /study/kfId/ to documents tab
  src/components/StudyNavBar/StudyNavBar.js
  src/routes/index.js
Labels: bug

#960 ✨ Open description links in new tab
  src/components/ReleaseList/ReleaseList.js
  src/documents/components/FileDetail/FileDescription.js
  src/documents/components/FileDetail/FileDetailModal.js
  src/documents/components/FileDetail/VersionCard.js
  src/documents/components/FileList/FileElement.js
  src/documents/modals/VersionInfoModal.js
  src/documents/modals/index.js
  src/forms/StudyInfoForm/Steps/LogisticsStep.js
  src/releases/components/ReleaseDetail/MarkdownEditor.js
Labels: refactor

#959 ✨ Allow search study by slack channel name
  src/components/StudyList/StudyList.js
Labels: refactor

#963 💄 Only show enabled services in new release form
  src/releases/forms/NewReleaseForm.js
  src/releases/queries.js
  src/releases/views/NewReleaseView.js
Labels: refactor

#974 ✅ Fix tests
  .circleci/config.yml
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  cypress/integration/invites/invite_user.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  docker-compose.yml
  src/modals/InviteModal.js
Labels: bug

#979 ✨ Search studies within new release form
  src/releases/components/StudyTable/StudyTable.js
  src/releases/forms/NewReleaseForm.js
Labels: feature

#978 ✨ Release pagination
  src/releases/components/ReleaseTable/ReleaseController.js
  src/releases/components/ReleaseTable/ReleaseTable.js
  src/releases/components/ReleaseTable/index.js
  src/releases/queries.js
  src/releases/views/HomeView.js
Labels: feature
