Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-12, with the labels that each got.

#1148 ✨ Add new Study fields
  src/common/notificationUtils.js
  src/components/StudyInfo/__test__/__snapshots__/ProgressBar.test.js.snap
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/state/fragments.js
Labels: feature

#1152 💄 Refactor UI margins and filter condition
  src/admin/views/EventsView.js
  src/admin/views/UsersView.js
  src/components/ReleaseList/ReleaseList.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
Labels: refactor, design

#1150 🏷 Release 0.25.0
  CHANGELOG.md
Labels: release

#1155 ✨ Add filters for latest releases list
  src/App.css
  src/releases/components/ReleaseTable/ReleaseController.js
  src/releases/components/ReleaseTable/ReleaseTable.js
  src/releases/queries.js
Labels: feature
