Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-06, with the labels that each got.

#1047 💄 Update release table started at time format
  src/releases/components/ReleaseTable/CreatedAt.js
  src/releases/components/ReleaseTable/ReleaseTable.js
Labels: refactor

#1052 💄 Adjust document table file name and tags display
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileFolder/FileFolder.js
  src/documents/components/FileFolder/FileSimpleElement.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/ReviewFiles/ReviewFileElement.js
Labels: bug, refactor

#1054 ✨ Click on tag to filter files from document list and review add document table
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileFolder/FileFolder.js
  src/documents/components/FileFolder/FileSimpleElement.js
  src/documents/components/FileFolder/FileSimpleList.js
  src/documents/components/FileList/FileElement.js
  src/documents/components/FileList/FileList.js
  src/documents/components/ReviewFiles/ReviewFileElement.js
  src/documents/components/ReviewFiles/ReviewFileList.js
  src/documents/components/ReviewFiles/ReviewFileSection.js
  src/documents/views/StudyFilesListView.js
Labels: feature

#1043 ✨ Add additional customized information field for study and save as json string
  package.json
  src/components/StudyNavBar/StudyNavBar.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/AdditionalFields.js
  src/forms/StudyInfoForm/Steps/CustomLink.js
  src/forms/StudyInfoForm/Steps/CustomParagraph.js
  src/forms/StudyInfoForm/Steps/index.js
  src/state/fragments.js
  src/views/StudyInfoView.js
  yarn.lock
Labels: component, feature

#1057 🐛 Fix editing/linking/unlinking Cavatica projects error
  src/common/enums.js
  src/components/CavaticaProjectList/CavaticaProjectList.js
  src/documents/modals/UploadWizard/UploadWizard.js
  src/modals/EditProjectModal.js
  src/views/CavaticaBixView.js
Labels: bug

#1058 🐛 Fix study release version display bug
  src/releases/components/StudyTable/StudyTable.js
Labels: bug

#1044 ✨ Organization switcher
  cypress/fixtures/example.json
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  src/components/Header/Header.js
  src/components/StudyList/ActionButtons.js
  src/components/StudyList/__tests__/__snapshots__/ActionButtons.test.js.snap
  src/components/StudyList/__tests__/__snapshots__/StudyTable.test.js.snap
  src/modals/InviteModal.js
  src/state/queries.js
  src/views/StudyListView.js
Labels: feature

#1055 ✅ Update tests for organization changes
  cypress/fixtures/example.json
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
Labels: refactor

#1053 ✨ Organizations admin view
  src/admin/components/OrganizationList/OrganizationItem.js
  src/admin/components/OrganizationList/OrganizationList.js
  src/admin/components/OrganizationList/index.js
  src/admin/forms/EditOrganizationForm.js
  src/admin/fragments.js
  src/admin/mutations.js
  src/admin/queries.js
  src/admin/views/OrganizationsView.js
  src/admin/views/index.js
  src/components/Header/Header.js
  src/routes/index.js
Labels: feature

#1062 🐛 Fix study collaborator list display error
  src/components/CollaboratorsList/CollaboratorsList.js
Labels: bug

#1059 ♻️ Attach organization to invites
  src/modals/AddCollaboratorModal.js
  src/modals/InviteModal.js
Labels: refactor

#1061 ✨ Add org to new studies
  cypress/integration/studies/add_study.spec.js
  cypress/integration/studies/study_list.spec.js
  src/views/NewStudyView.js
Labels: feature

#1063 ✅ Update cypress tests for new mock data
  cypress/integration/documents/document_config.spec.js
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  cypress/integration/studies/study_list.spec.js
  cypress/integration/studyInfo/collaborators.spec.js
  cypress/integration/studyInfo/logs.spec.js
Labels: refactor
