Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-02, with the labels that each got.

#957 ✨ App banners
  src/App.css
  src/admin/common/bannerUtils.js
  src/admin/components/BannerTable/ActionButtons.js
  src/admin/components/BannerTable/BannerDate.js
  src/admin/components/BannerTable/BannerMessage.js
  src/admin/components/BannerTable/BannerTable.js
  src/admin/components/BannerTable/BannerToggle.js
  src/admin/components/BannerTable/Creator.js
  src/admin/components/BannerTable/Severity.js
  src/admin/components/BannerTable/index.js
  src/admin/forms/BannerForm.js
  src/admin/mutations.js
  src/admin/queries.js
  src/admin/views/BannersView.js
  src/admin/views/EditBannerView.js
  src/admin/views/NewBannerView.js
  src/admin/views/index.js
  src/common/dateUtils.js
  src/components/Header/AppBanner.js
  src/components/Header/Header.js
  src/components/Header/index.js
  src/routes/index.js
Labels: feature

#986 ✨ Allow releases to be renamed
  src/releases/components/ReleaseDetail/ReleaseHeader.js
  src/releases/components/ReleaseDetail/ReleaseName.js
  src/releases/views/ReleaseDetailView.js
Labels: feature

#985 📈 Release charts
  package.json
  src/App.css
  src/releases/components/ReleaseActivity/ReleaseActivity.js
  src/releases/components/ReleaseActivity/calendar.js
  src/releases/components/ReleaseActivity/index.js
  src/releases/components/ReleaseBarChart/ReleaseBarChart.js
  src/releases/components/ReleaseBarChart/bar.js
  src/releases/components/ReleaseBarChart/index.js
  src/releases/queries.js
  src/releases/routes.js
  src/releases/views/NavigationView.js
  src/releases/views/StatsView.js
  src/releases/views/index.js
  yarn.lock
Labels: feature

#980 ✨ Filter logs by job
  src/admin/components/JobsList/JobsList.js
  src/admin/queries.js
  src/admin/views/LogsView.js
Labels: feature

#981 ✨ Allow expired invites to be resent
  cypress/integration/invites/invite_user.spec.js
  src/admin/views/PendingInvitesView.js
Labels: feature

#943 ✨ Add file folder feature for study documents
  cypress/integration/documents/document_detail.spec.js
  cypress/integration/documents/document_list.spec.js
  package.json
  src/App.css
  src/common/treeDataUtils.js
  src/documents/components/FileDetail/FileName.js
  src/documents/components/FileList/FileFolder.js
  src/documents/components/FileList/FolderItem.js
  src/documents/views/StudyFilesListView.js
  yarn.lock
Labels: feature

#988 ✨ Add investigator to study
  src/App.css
  src/components/StudyList/InvestigatorName.js
  src/components/StudyList/StudyList.js
  src/components/StudyList/StudyTable.js
  src/forms/StudyInfoForm/NewStudyForm.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
  src/state/fragments.js
  src/state/queries.js
Labels: feature

#987 🏷 Release 0.19.0
  CHANGELOG.md
Labels: release

#961 🐛 Fix footer backend version link
  src/components/Footer/Footer.js
Labels: bug

#989 ✨ Add file folder detail view with folder tree view on the side
  package.json
  src/App.css
  src/common/treeDataUtils.js
  src/components/StudyList/StudyTable.js
  src/documents/components/FileActionButtons/FileActionButtons.js
  src/documents/components/FileDetail/FileDetail.js
  src/documents/components/FileDetail/FileTags.js
  src/documents/components/FileFolder/FileFolder.js
  src/documents/components/FileFolder/FileSimpleElement.js
  src/documents/components/FileFolder/FileSimpleList.js
  src/documents/components/FileFolder/FolderActionButtons.js
  src/documents/components/FileList/FolderItem.js
  src/documents/views/StudyFilesListView.js
  yarn.lock
Labels: feature, refactor
