Repository kids-first/kf-ui-data-tracker, pull requests merged in 2021-08, with the labels that each got.

#1076 ✨ Add data templates tab under study for downloading templates
  src/App.css
  src/admin/components/UserList/UserItem.js
  src/admin/views/UsersView.js
  src/assets/templateHelper.jpeg
  src/common/enums.js
  src/components/Header/Header.js
  src/components/StudyNavBar/StudyNavBar.js
  src/components/StudyNavBar/__tests__/__snapshots__/StudyNavBar.test.js.snap
  src/components/TemplateList/TemplateList.js
  src/documents/components/helpers/DataTemplatesHelp.js
  src/documents/components/helpers/index.js
  src/routes/index.js
  src/state/queries.js
  src/views/DataTemplatesView.js
  src/views/NavBarView.js
  src/views/index.js
Labels: feature

#1085 ✨ Add template admin view with create/edit/delete template function
  src/App.css
  src/admin/views/TemplatesView.js
  src/admin/views/index.js
  src/common/enums.js
  src/common/sortUtils.js
  src/components/TemplateList/TemplateList.js
  src/forms/DataTemplateForm/DataTemplateForm.js
  src/forms/DataTemplateForm/FieldTableRow.js
  src/modals/DataTemplateConfirmModal.js
  src/routes/index.js
  src/state/mutations.js
  src/views/DataTemplatesView.js
Labels: feature

#1088 🐛 Fix admin templates organization options
  src/admin/views/TemplatesView.js
  src/components/TemplateList/TemplateList.js
Labels: bug

#1090 🐛 Fix study data template tab displaying error
  src/components/TemplateList/TemplateList.js
Labels: bug

#1089 🏷 Release 0.22.0
  CHANGELOG.md
Labels: release

#1091 ✨ Add read-only template modal to the list in study data template tab
  src/admin/views/TemplatesView.js
  src/components/TemplateList/TemplateList.js
  src/forms/DataTemplateForm/DataTemplateForm.js
  src/modals/DataTemplateEditModal.js
  src/views/DataTemplatesView.js
Labels: feature

#1093 🏷 Release 0.22.1
  CHANGELOG.md
Labels: release

#1112 🐛 Minor bug fix around study info and event list
  src/admin/views/EventsView.js
  src/common/enums.js
  src/components/StudyList/InvestigatorName.js
  src/forms/StudyInfoForm/Steps/InfoStep.js
Labels: refactor, bug
